### ISSUE TITLE
Letzte Version auf Rechtschreibfehler prüfen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#1]
https://tools.adfc-hamburg.de/t30-paten/version0.0.7/

E-Mail abc Passwort: abc
je nach Kenntnisstand bitte entweder die Fehler an dieses Ticket oder gleich im Git beheben

**Comment by WiebkeADFC** [comment]
passiert im laufenden Betrieb ständig
