### ISSUE TITLE
T30 Antrag speichern und später weiter bearbeiten

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#10]
Es gäbe eine einfache Möglichkeit den bearbeitungsstand zu speichern. Dazu müsste man aber den Ablauf umstellen:

Zuerst sich anmelden mit einer E-Mailaddresse und dann diese bestätigen.
Im Anschluss kann man dann alle Aktionen machen  z.B. 

- Institutionen  / Standorte hinzufügen
- Mails vorbereiten
- Mails verschicken
- Daten von den Standorten zur Änderung vorschlagen
- Persönliche Daten ändern

Das hätte viele Vorteile, z.B. das wir nicht so viele Daten speichern müssen und hoffen müssen, dass die Person auf den Link klickt und das es nur ein Forumlar für persöliche Daten gibt etc.

**Comment by WiebkeADFC** [comment]
einfach ist gut, dann machen wir das so, oder?

**Comment by tabacha** [comment]
Nachteil wäre das man abwarten muss, bis man die Mail vom ADFC erhalten hat. Das dauert je nach E-Mail-Anbieter 1 Minute bis 1h. Da können wir ggf. schon mal jemanden verlieren. 
Ich wäre aber trotzdem dafür.

**Comment by WiebkeADFC** [comment]
finde ich OK. Ist nachvollziehbar, dass man sich erst registrieren muss, um aus einem Webtool direkt eine Mail an die Polizei zu verschicken.

**Comment by tabacha** [comment]
Funktioniert in Version 0.0.7

**Comment by WiebkeADFC** [comment]
finde ich klasse!!
