### ISSUE TITLE
Bearbeiten, Angaben zu Straßenabschnitten... , Überschriften von Eingabefeldern

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#105]
Die Änderung der Größe der Überschrift vom Eingabefeld, wenn man einen Angabe gemacht hat, ist nicht so leicht nachvollziehbar/verwirrend.
Ich würde Überschriften in einer fixen Größe bevorzugen, so wie die unbearbeiteten Felder. 

Der Abstand zwischen einem Erklärtext unterhalb eines Eingabefelds und der nächsten Überschrift für ein Eingabefeld ist zu gering.

**Comment by tabacha** [comment]
Bahnhof. Lass mal Montag dazu telefonieren
