### ISSUE TITLE
Tempo 30 fordern, Dein Bezug zur Einrichtung als Pflichtfeld kennzeichnen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#106]
Der E-Mailtext erscheint erst, wenn man den Bezug zur Einrichtung ausgefüllt hat. Dann müsste das Feld auch als Pflichtfeld gekennzeichnet sein.

**Comment by tabacha** [comment]
Bei mir erscheint der Text schon früher. Bitte neu anmelden und nochmal testen, kann ein Folgefehler sein. Ansonsten bitte mal Adblocker, Browser etc. prüfen/ mitteilen.

**Comment by WiebkeADFC** [comment]
Läuft!
