### ISSUE TITLE
Meine Tempo 30, E-Mail wurde verschickt, bearbeiten-Button sinnlos

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#108]
Wenn eine E-Mail schon verschickt wurde, kann man den Straßenabschnitt ja nicht mehr bearbeiten. Dann macht Bearbeiten-Button ja keine Sinn mehr. Besser wäre ein "view" Button, über den man sich die E-Mail noch mal angucken kann.

**Comment by tabacha** [comment]
Doch man kann ja angeben, dass die Poilizei sich gemeldet hat, und Schilder aufstellen will, oder das Bezirkspolitiker X von der FDP sich für die Schule einsetzt ...

Ich gebe zu, das was dann dahinter kommt ist im Moment etwas verwirrend, liegt aber zum Teil am nicht vorhandenen Backend.

**Comment by WiebkeADFC** [comment]
ich habe eine Ticket aufgemacht, dass den Vorgang genauer beschreibt: https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/issues/127
