### ISSUE TITLE
Mein Tempo 30 Eingaben, Straßenabschnitt  statt Straße

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#109]
Jetzt werden ja pro Straßenabschnitt einzelne Mails generiert, insofern müssten bei "Meine T30 Forderungen" auch die Mails/Entwürfe für die einzelnen STraßenabschnitte aufgeführt sein, mit der Spalte "Strraßenabschnitt".

**Comment by tabacha** [comment]
Ich denke die Straße ist dafür dann überflüssig, oder? Dann können wir daraus auch Straßenabschnitt machen?

**Comment by WiebkeADFC** [comment]
Ich denke auch, ist bestimmt auch leichter zu verstehen. Spaltentitel und Bezug in der Datenbank ändern.

**Comment by WiebkeADFC** [comment]
Was für ein Label kriegt denn so ein Auftrag? Nachdem diese Seite erstellt wurde, haben wir das Konzept auf STraßenabschnitte umgestellt, und dann ist diese Änderung ja eine logische Folge. Ist das dann ein Bug, weil logischer Fehler? Oder Enhancement, weil wir diese Anforderung vorher noch nicht formuliert hatten?

**Comment by tabacha** [comment]
Enhancement: Als es gebaut wurde, war es richig. Jetzt wird die Anwendung um eine andere Logik erweitert. Das ist bei unserem Projekt nicht so super wichtig, aber bei einer Software-Entwicklunsabteilung ist jeder Bug eigentlich ein Grund für eine Nachschulung des Entwicklers ;-)  Weil der nicht planbar ist, ist ein Bug immer doof.

**Comment by WiebkeADFC** [comment]
Danke!

**Comment by WiebkeADFC** [comment]
dieser Inhalt doppelt sich mit https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/issues/127
