### ISSUE TITLE
Luft- und Lärmwerte einbinden? Klären

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#11]
Sven: Ich frage mich wie wichtig die Schadstoff und Lärmwerte in der E-Mail wirklich 
sind, weil das ist im Zweifel recht viel arbeit und wenig representativ. Denn 
die meisten Schüler sind ja nicht direkt mit ihrem Klassenzimmer an der Straße 
und es gibt dann Situationen wo z.B. nur die Turnhalle  zur Straße liegt und 
wir dann sagen: Das ist das zu laut und die Politik sagt: Da ist nur die 
Turnhalle und da machen die Schüler sowieso krach.

Jens: >> gute Frage - es hängt denke ich davon ab wie wir die Themne vermischen  wollen - dafür spricht das ja insbesondere übers Lärm-Thema eigentlich auch immer die Frage des ganztäglichen Tempo30 geklärt ist (Schule Tag - Lärm-Nachts) und wir aber auch ein Argument dafür haben warum eigentlich die ganze Straße auf T30 sollte .. < vielleicht "reduziert" sich der extra Aufwand durch den kommentar von mir oben bezüglich der Daten zur großen Anfrage?

**Comment by tabacha** [comment]
Beschluß: Wir lassen es erstmal weg
