### ISSUE TITLE
Tempo 30 fordern, Erklärtext zuständiges PK einfügen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#114]
Sven: "Wir haben für die Straßenabschnitte im Moment keine Geo-Koordinaten. Wenn jetzt eine Turnhalle von der Schule in einem anderen Polizei Gebiet liegt, dann gibt das Konfussion. Bitte schreibe, wie wir das den User klar machen wollen."

Verstehe also richtig: Das Polizeikommissariat wird nach der Adresse der Einrichtung ausgewählt? Es kann also sein, dass ein Straßenabschnitt ein anderes PK hat als die Einrichtungsadresse. Ich würde einfach mal davon ausgehen, dass die Forderungsmail dann an das richtige PK weitergeleitet wird oder sich die PKs so aufteilen, dass immer eines für eine ganze soziale Einrichtung zuständig ist. 

Bei der Turnhalle sehe ich kein Problem, wenn sie als eigene Einrichtung angelegt ist und die Adresse korrekt angegeben wird. Dann kriegt sie ja eine eigene Geo-Koordinate. 

Vorschlag: auf der Seite "Tempo 30 fordern" im Abschnitt Forderungsmail ein Erläuterungstext unter die Bereichsüberschrift "Forderungsmail.."

"Das zuständige Polizeikommissariat wird automatisch anhand der Adresse der sozialen Einrichtung ermittelt."

**Comment by WiebkeADFC** [comment]
Ich meine, hier müsste nur ein Textfeld eingefügt werden, ich sehe da kein Problem, das wir lösen müssen.

**Comment by tabacha** [comment]
Du hast den Vorschlag gemacht:
>Vorschlag: auf der Seite "Tempo 30 fordern" im Abschnitt Forderungsmail ein Erläuterungstext unter die Bereichsüberschrift "Forderungsmail.."

>"Das zuständige Polizeikommissariat wird automatisch anhand der Adresse der sozialen Einrichtung ermittelt."
und ich habe das umgesetzt

**Comment by WiebkeADFC** [comment]
allles klar, ich schließe dieses Issue, warum hast du das in Test verschoben?
