### ISSUE TITLE
Karte soz. Einrichtungen mit bestehender Karte Grenzwerte und Tempo 30 Anträge integrieren?

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#12]
Hier https://hamburg.adfc.de/verkehr/themen-a-z/tempo-30/laeuft/karte-antraege-und-belastungen/#11/53.5600/10.0200
gibt es ja schon Karte mit Luft- und Lärmwerten und den Orten der privaten Tempo 30 Anträge. Kann die Karte für soziale Einrichtungen hier integriert werden? Das wäre sehr praktisch für die Kampagnen-Kommunikation.

**Comment by tabacha** [comment]
Ja, ginge
