### ISSUE TITLE
Meine T30-Forderungen, Inhalte und Landingpages 

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#127]
Egal auf welchen Button ich in der Liste meiner Forderungen klicke, lande ich jetzt immer auf der Seite "Tempo 30 fordern" mit der Einstellung "Ich möchte etwas korrigieren". Das ist noch nicht sinnvoll. 

1. Issue https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/issues/124 klären.

2.  Button zu Bearbeiten-Seite, Button zu abgeschickte E-Mail lesen.

**Comment by tabacha** [comment]
Das liegt daran, dass es noch ein Stub ist. Biite jetzt nicht so tun, als wäre schon alles fertig.

**Comment by tabacha** [comment]
Können wir das Ticket bitte schließen? Die Funktionalität ist noch nicht da. Oder als Enhancement, dann aber bitte mit klarer Ansage, wie die Seite für wlechen Status aussehen soll.

**Comment by WiebkeADFC** [comment]
In der Liste "Meine Tempo 30 Forderungen" werden nur Straßenabschnitte, die als "Hier fehlt Tempo 30" kategorisiert sind, entweder als Entwurf oder als abgeschickte E-Mail gelistet. 
Reihenfolge: Oben die Entwürfe, dann die abgeschickten Mails. Innerhalb der Status alfabetisch sortiert nach Name der Einrichtung, dann Straßenabschnitt. 

Spaltentitel mit (Angabe in Zelle bzw. Button): 
Einrichtung (Name d. Einrichtung, ggf. mit Nebenstelle (mit Link zur Detailseite? dann können die Leute von hier aus gleich weitere Mails für andere Straßenabschnitte derselben Einrichtung verfassen))
Straßenabschnitt
Status (E-Mail als Entwurf gespeichert; E-Mail abgeschickt)
E-Mail (E-Mail bearbeiten; E-Mail ansehen)
Verlauf aktualisieren (Stift zu Einrichtung bearbeiten/jeweiligem Straßenabschnitt, wo Tempo-30-Status, Verlauf der Forderung und sonstige Angaben zur Einrichtung/Straßenabschnitt geändert und Straßenabschnitte hinzugefügt werden können)

Wenn Status Entwurf, dann Button zu E-Mailentwurf und zu Einrichtung bearbeiten/jeweiliger Straßenabschnitt
Wenn Status E-Mail versand, dann Button zu archivierter E-Mail und zu Einrichtung bearbeiten/jeweiliger Straßenabschnitt
