### ISSUE TITLE
Mailtext erarbeiten

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#13]
Welcher Text soll (vorausgefüllt) im E-Mail  stehen und (durch den User geändert) an die Polizei geschickt werden?

**Comment by WiebkeADFC** [comment]
gerne Besprechung in PG Tempo 30

**Comment by tabacha** [comment]
Auch klären: Wer ist empfänger

**Comment by WiebkeADFC** [comment]
Hallo Sven,
ich habe noch mal den Forderungstext überarbeitet. 

Mailtext Forderung T30sE

Betreff: Tempo 30 „Straßen“ an „Name Einrichtung, ggf. Nebenstelle“ 

Mail: 
Sehr geehrte Damen und Herren,

Mein Name ist „Vor-, Nachname“. Ich bin „Bezug zur Einrichtung“ der/des „Art der Einrichtung im Genitiv“ „„Name der Einrichtung (in  Gänsefüßchen)““, „Adresse“. Im Umfeld dieser Einrichtung „ , ggf. Nebenstelle“ ist leider noch kein Tempo 30 eingeführt. 

Ich ersuche Sie hiermit, an diesem an die/das „Art der Einrichtung“ angrenzenden Straßenabschnitt Tempo 30 einzuführen: 

„Straßenabschnitt 1“, Begründung: 
Haupteingang zur Einrichtung und/oder Quell- und Zielverkehr

(Unzutreffendes bitte streichen, gerne durch Beschreibungen der Umstände vor Ort ergänzen)
Aus meiner Sicht sind die Kinder/ Schüler*innen/ Bewohner*innen/ Patient*innen/ Besucher*innen, die im Umfeld der/des „Art der Einrichtung im Genitiv“ am Verkehr teilnehmen, nicht ausreichend vor dem schnellen KFZ-Verkehr geschützt. Die KFZ-Fahrer*innen müssen durch ein geringeres Tempo in die Lage versetzt werden, besondere Aufmerksamkeit walten zu lassen.

Die Änderung für den KFZ- „wenn Bus, dann : „und ggf. den Busverkehr halte“ ich angesichts des Sicherheitsgewinns für angemessen. Der Sicherheit muss Vorrang vor Geschwindigkeit gewährt werden. 
„ggf. Begründung Bus Verlangsamung“ (Die Busse verlangsamen an der Stelle ohnehin wegen einer Bushaltestelle/der abbiegenden Buslinie ihre Fahrt.)

Laut § 45 Absatz 9 Satz 4 Ziffer 6 der StVO in Verbindung mit der Verwaltungsvorschrift zu § 45 StVO soll zum Schutz besonders schützenswerter Personen im Umfeld sozialer Einrichtungen, also dort wo Haupteingänge sind oder Quell- und Zielverkehr zur Einrichtung herrscht, regulär Tempo 30 gelten, ohne dass eine  besondere Gefahrenlage erwiesen ist. 
 
Vielen Dank und mit freundlichen Grüßen

Willy Speichenbruch
„Straße Hausnummer“
„PLZ“ „Ort“
„Telefon“

--
Diese E-Mail wurde durch das T30-Tool des ADFC-Hamburg verschickt, mehr Infos dazu unter
https://hamburg.adfc.de/hast-nicht-gesehen-FIXME
