### ISSUE TITLE
Spenden Sammeln

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#138]
Idee: Nach dem Versand einer E-Mail wird eine Seite eingebunden, in der um Spenden gebeten wird.

Vor der Umsetzung soll Georg gefragt werden, ob das Datenschutzrechrlich in Ordnung ist.
Wenn das geklärt ist, bitte Ticket Assigi auf tabacha stellen.

**Comment by WiebkeADFC** [comment]
Ich habe die Mail an GEorg geschrieben.

**Comment by WiebkeADFC** [comment]
Georg ist einverstandne, habe ihn letzten mündlich gefragt.

**Comment by tabacha** [comment]
@JulianLindner @WiebkeADFC  Bitte Pull-Request #325 ansehen.
