### ISSUE TITLE
"Beziehung zur Einrichtung" unter Einrichtung

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#14]
Damit der User das Klappfenster Aktion nicht überseht. Sinn der Trennung ist für den User nicht ersichtlich. Übersichtlichkeit wird bei den zwei kleinen Punkten nicht schlechter. 
Alternativ: Klappfenster nur für "Stand der Dinge", da dies der einzige Punkt ist, den der User im Laufe der Aktion wieder bearbeitet.

**Comment by WiebkeADFC** [comment]
Wenn die beiden Klappfenster zusammengefasst werden, sind manche der anderen Issues nicht mehr nötig.

**Comment by tabacha** [comment]
Beschluß der Projektgruppe: Unter Einrichtung auch die Beziehung packen und Stand der Dinge unter Aktion
