### ISSUE TITLE
Passwort aktiv bis 17.11!

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#148]
Aktionspasswort ist: xxxxx 
 soll bis 10.11. aktiv sein.

**Comment by tabacha** [comment]
Das ist nicht so optimal, hier ein Passwort zu hinterlegen, was von der ganzen Welt gelesen werden kann

**Comment by tabacha** [comment]
Bitte auf https://t30forderung.hamburg.adfc.de/ testen

**Comment by WiebkeADFC** [comment]
getestet im Liveding, richtiges Stichwort funktionierte, aber Mail an Polizei wurde nicht versandt. 

Eingabe falsches Stichwort mit Funktion "E-Mail speichern" getestet, es gab keine Fehlermeldung, aber das ist auch schwierig zu testen, weil "E-Mail speichern" auch ohne Stichwort gehen soll. 

Ich habe falsches Stichwort nicht mit E-Mailversand getestet, weil ich keine falsche Mail an die Polizei riskieren will. Checke ich am Donnerstag mit Kumpel.

**Comment by tabacha** [comment]
@WiebkeADFC Kannst du das bitte im Testsystem mit dem Passwort "aktion" testen.

Ich hatte schon https://github.com/ADFC-Hamburg/adfc-t30-api/issues/84 aufgemacht. Das hier ist kein Bug oder er ist doppelt.

**Comment by JulianLindner** [comment]
Das Passwort soll nun bis zum 17.11 aktiv sein

**Comment by tabacha** [comment]
Bei mir stimmt der Text (siehe Screenshot) oder ich übersehe etwas.


![2019-11-06 12_36_45-Window](https://user-images.githubusercontent.com/1101544/68295213-2ab5bc80-0092-11ea-8cb0-648e225a024d.png)

**Comment by JulianLindner** [comment]
Version 1.0.1. über dem Mailversand: 
![grafik](https://user-images.githubusercontent.com/19272727/68298346-656f2300-0099-11ea-8d45-7d42230756c2.png)

**Comment by tabacha** [comment]
In der Testversion ist es der 1.12

**Comment by WiebkeADFC** [comment]
Hallo @tabacha, es wäre super, wenn du den 17.11. als Enddatum für das Stichwort einrichten könntest. Am 18.11. ist die Veranstaltung in Barmbek, da wäre es gut, wenn Kitas und Schulen ohne Stichwort funktionieren. 
Danke

**Comment by tabacha** [comment]
Nochmal: WO IN DER LIVE VERSION STEHT EIN ANDERES DATUM ?

**Comment by WiebkeADFC** [comment]
Vielleicht nen Missverständnis. Mir geht es darum, dass die Stichwort-Funktion im Backend nur bis 17.11. läuft.

**Comment by WiebkeADFC** [comment]
Julian guckt gleich in der Liveversion

**Comment by JulianLindner** [comment]
In der Liveversion ist das alles richtig!
