### ISSUE TITLE
Karte und Liste Farblegende einfügen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#149]
Jeweils den Stern in der Farbe mit Text: 

"Ein Stern markiert eine soziale Einrichtung.

blau: Bitte prüfen, d. h. ggf. vor Ort relevante Straßenabschnitte im Umfeld der Einrichtung überprüfen und deren Tempo-30-Status eingeben.

rot: Mail versenden. Hier wurde noch nicht für alle relevanten Straßenabschnitte im Umfeld der Einrichtung ohne Tempo 30 eine Mail versandt.

orange: Forderung gestellt. Für alle relevanten Straßenabschnitte im Umfeld der Einrichtung ohne Tempo 30 wurde bereits eine Mail versandt. 

grün: OK. An allen relevanten Straßenabschnitten im Umfeld der Einrichtung gilt Tempo 30.

gelb: Umsetzung beobachten. An mindestens einem relevanten Straßenabschnitt im Umfeld der Einrichtung wurde Tempo 30 bereits angeordnet, aber noch nicht eingeführt.  

schwarz: Abgelehnt. Für mindestens einen relevanten Straßenabschnitt im Umfeld der Einrichtung hat die Behörde Tempo 30 abgelehnt."

Legende gerne zum Ein- und ausklappen wie bei den Tipps.

**Comment by tabacha** [comment]
siehe auch #47
