### ISSUE TITLE
Von > Übersichtsseite > bearbeiten eingeklappte Reiter

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#15]
Wenn man in der Übersichtsseite der Einrichtungen rechts neben der Einrichtung auf "bearbeiten" klickt, landet man auf dem Klappfenster "Aktion". Sinniger fände ich auf dem Klappfenster "Einrichtung" zu landen.

**Comment by tabacha** [comment]
Ich denke das man die Daten der Einrichtung schnell eingeben hat, und dann immer wieder nur den Stand der Dinge editiert. Deshalb das so.

**Comment by WiebkeADFC** [comment]
Ach so. Ich dachte für die User wäre es ganz angenehm auf einer "bekannten" oder "erwarteten" Seite zu landen. Alternativ könnte sie auf der Formularseite mit eingeklappten Reitern landen.

**Comment by tabacha** [comment]
Eingeklappte Reiter finde ich auch gut.

**Comment by WiebkeADFC** [comment]
Ja bitte
