### ISSUE TITLE
Such-Button bei Liste und Karte

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#150]
Das Suchfeld bei Liste und Karte orange hinterlegen. 
Text komplett sichtbar, also einschließlich PLZ

**Comment by tabacha** [comment]
Eine Suche bei der Karte ist extrem aufwendig. Das lehne ich ab.

**Comment by tabacha** [comment]
![Screenshot_20191020_161639](https://user-images.githubusercontent.com/1101544/67160845-2df03f00-f355-11e9-8cec-33131aa74846.png)

Ich habe im PR 150 mal die Sucheingabe breiter und mit einem Icon versehen

**Comment by tabacha** [comment]
Für die Kartensuche gibt es IMHO  bereits  einen Issue

**Comment by WiebkeADFC** [comment]
Danke
