### ISSUE TITLE
Zurück-Klick von Details auf Karte

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#153]
Testuser wünscht sich, dass derselbe Kartenausschnitt erscheint, von dem er aus er auf "Details" geklickt hat.

**Comment by tabacha** [comment]
Verstehe ich nicht: Bitte genauer beschreiben

**Comment by WiebkeADFC** [comment]
Der Tester hat in die Karte reingezoomt, auf den Stern geklickt, im Klappfenster auf Details. Von Details auf "Zurück" und dann hat die Karte im Standardzoom gesehen, wäre aber gerne in den Ausschnitt zurückgekommen, von dem aus er Details geklickt hat.

**Comment by tabacha** [comment]
Das ist recht komplex, würde ich erstmal lassen.

**Comment by WiebkeADFC** [comment]
OK, ist ja auch low prio
