### ISSUE TITLE
Buttons Detail und Bearbeiten tauschen und umbenennen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#155]
Die Testuser suchen intensiv, wo kann ich die Mail schreiben? Die Buttons haben sie nicht verstanden. 
Reihenfolge der Buttons Details und Bearbeiten in Liste und Klappfenster tauschen
Bearbeiten umbenennen in: 
Angaben zur Einrichtung oder den Straßenabschnitten in deren Umfeld eingeben oder ändern. 
Details umbenennen in: 
Details ansehen, von hier Tempo-30-Mail generieren

**Comment by tabacha** [comment]
![Screenshot_20191020_162842](https://user-images.githubusercontent.com/1101544/67161010-d18e1f00-f356-11e9-8ea8-1f1f8df969eb.png)
![Screenshot_20191020_162908](https://user-images.githubusercontent.com/1101544/67161014-d4890f80-f356-11e9-9b7a-039e2575e155.png)

Das nimmt zu viel Platz weg

**Comment by tabacha** [comment]
@WiebkeADFC  Ich habe den Text in das Mouse-Over gepackt. Ist das so okay?
Ist Pull-Request #163

**Comment by WiebkeADFC** [comment]
Ja, danke
