### ISSUE TITLE
Tempo 30 Status

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#159]
Reihenfolge der Status ändern: 

1. Hier fehlt...

2. Hier ist...

3. angeordnet...

4. hinzufügen: Hier wurde Tempo 30 bereits vor der ADFC-Kampagne beim zuständigen Polizeikommissariat eingefordert, aber noch nicht entschieden. 

5. abgelehnt...

6. als letztes "Keine Angabe" 

4. muss bei der Berechnung des Status für die ganze Einrichtung so behandelt werden, als hätte jemand eine Mail für den Straßenabschnitt versand.

**Comment by tabacha** [comment]
Wo?

**Comment by tabacha** [comment]
Wo?

**Comment by WiebkeADFC** [comment]
Beim DropdownMenü Tempo 30 Status bei STraßenabschnitt bearbeiten. Danke

**Comment by tabacha** [comment]
@WiebkeADFC  @JulianLindner  Punkt 4 finde ich es problematisch das geanu so zu speichern, als hätten wir eine E-Mail verschickt. Da befürchte ich, dass wir da später nicht mehr durchblicken. Die Logik ist ja im Moment gerade so, dass man den Zustand: Wir haben mit dem Tool-T30 gefordert hat, nur dardurch auswählen kann, dass man eine E-Mail verschickt. Im Zweifel kann der User ja auch eine weitere E-Mail durch das Tool erzeugen.

**Comment by tabacha** [comment]
Punkt 6 muss IMHO als erste kommen, weil das der Default-Wert ist, sonst muss der User "Hochscrollen"

**Comment by WiebkeADFC** [comment]
ich verstehe die Argumente, bei Default Wert gehe ich auch mit. 
Für 4. schlage ich vor, dass wir das erst mal so lassen und damit auch an Start gehen können und die Problematik noch mal besprechen.

**Comment by tabacha** [comment]
TODO: Hier Fehlt und Hier ist Tempo 30 vertauschen
