### ISSUE TITLE
Doppelte Issues aufräumen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#160]
Es ist total demotivierend wenn es für ein und die selbe sache, zwei oder mehr Tickets gibt.

**Comment by tabacha** [comment]
@WiebkeADFC Du machst gegühlt ständig neue Issues auf, für Dinge die schon einen Issue haben. So bekommen wir nie einen Überblick. Dieser Issue ist für mich der wichtigste!!!!

**Comment by WiebkeADFC** [comment]
Hi Sven, 
ja, das sehe ich komplett ein. Julian hatte letzte Woche die Aufgabe, die Issues aufzuräumen, er war aber die ganze Woche krank und ich hatte leider keine Zeit. Ist ja nicht umsonst, dass ich an nem Sonntag im Büro sitze...  Ich habe Testuser-Sessions gemacht mit Kollegen und bemühe mich jetzt die Erkenntnisse daraus in Github zu bringen, das ist echt schwierig, weil deren Blickwinkel so einiges aufwirft. Es tut mir leid, dass das jetzt son Chaos ist. Ich versuche morgen vormittag mehr Ordnung reinzbringen. Jetzt muss ich auch bald wieder nach Hause.

**Comment by tabacha** [comment]
Dann schönen Feierabend. Lass morgen früh telefonieren.

**Comment by tabacha** [comment]
@WiebkeADFC @JulianLindner  Mögt ihr bitte euch dem Ticket annehmen? Es gibt da IMHO immer noch uralte Issues die vermutlich geschlossen  werden können.
