### ISSUE TITLE
Forderungsmail: "Dein Bezug zur Einrichtung"

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#166]
Irritation bei Testuser. Kann diese Angabe von der SEite der Forderungsmaill zu "Bearbeiten" in den Abschnitt der Einrichtung umziehen? Als letzte Angabe bei der Einrichtung.

**Comment by WiebkeADFC** [comment]
war doch keine gute Idee, diese Angabe wird gerne geändert beim E-Mail verfassen.

**Comment by tabacha** [comment]
Ja
