### ISSUE TITLE
Forderungsmail, Bezug zur Einrichtung, Änderung in Mail übernehmen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#168]
Wenn ich den Bezug zur Einrichtung ändere, bleibt die erste Angabe im E-Mailentwurf unverändert. Änderungen sollen übernommen werden.

**Comment by tabacha** [comment]
Hast du die E-Mail bereits gespeichert? Dann hat das gespeicherte Vorrang. Ansonsten nicht.

**Comment by WiebkeADFC** [comment]
merkwürdig, als ich eben noch mal in der Forderungsmail den Bezug zur Einrichtung geändert habe, wurde die Änderung beim Schreiben in die Mail übertragen..
