### ISSUE TITLE
von "Meine Forderungsmails" zu "E-Mailentwurf"

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#169]
Wenn man bei "Meine Forderungsmails" auf  den E-Mail-Button klickt, kommt man auf die Forderungsmailseite im Stadium, dass man noch mal die Richtigkeit der Angaben bestätigen muss, auch wenn man das schon mal gemacht hat. Der User will aber direkt zum E-Mailentwurf.
 
Oder dient das der Sicherheit, dass man nicht mit von anderen geänderten Daten weiterarbeitet?

Ich bin der Meinung, dass, sobald jemand einen E-Mailentwurf gespeichert hat oder eine E-Mail versand hat, kann niemand anderes die Hausnummern des Straßenabschnitts bearbeiten. Ggf. muss der andere einen neuen Straßenabschnitt anlegen.

**Comment by tabacha** [comment]
@WiebkeADFC  Komisch: Bei mir ist dann: Ja die Daten sind korrekt ausgewählt. Auf welcher Version testest du?

Man kann den Straßenabschnitt noch bearbeiten. Erst wenn die E-Mail abeschickt wurde, geht das nicht mehr. Hab aber das Gefühl wir reden hier ständig um eine Gefahr, die nicht auftreten wird.

**Comment by WiebkeADFC** [comment]
In Version 44 geht es wieder
