### ISSUE TITLE
Speichern-Button in Klappfenstern "Einrichtung" + "Aktion'"

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#17]
Einfach zu finden, wenn man schnell raus will aus der Anwendung. Sucht man sonst in der Ansicht des Klappfensters vergeblich, findet man erst nach "weiter"-Klicken im Klappfenster "Aktion" oder unter E-Mail, je nach Bearbeitungsstatus. User weiß aber auch nicht, was "Weiter" bewirkt und traut sich vielleicht nicht, es zu klicken.

**Comment by tabacha** [comment]
Sollten wir in der Projektgruppe besprechen
