### ISSUE TITLE
Straße wird bei Registrierung nicht gespeichert

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#172]
Im E-Mailentwurf wird Straße und Hausnummer vom User-Profil nicht übernommen, unten bei den Angaben zum Ersuchenden.

**Comment by tabacha** [comment]
Analyse: Liegt nicht daran, dass die Straße nicht eingefügt wird, sondern dass bei der Registrierung die Straße nicht gespeichert wird.
