### ISSUE TITLE
Speichern auf der Bearbeiten-Seite und "Straßenabschnitt löschen" 

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#173]
Da wo jetzt der Button "diesen Straßenabschnitt löschen" ist, sollte ein Button "Angaben zum Straßenabschnitt speichern" hin, und der User verbleibt dann auf der Seite und kann weitere Straßenabschnitte hinzufügen. 

Sobald Angaben zum Straßenabschnitt gespeichert wurden, erscheint neben dem Button "Angaben zum Straßenabschnitt speichern" ein Button "Tempo 30 fordern", falls "Hier fehlt Tempo 30" angegeben wurde, und der User kommt direkt zum E-Mailentwurf für diesen Straßenabschnitt

Den blaue Button "speichern" umbenennen in "Alle Angaben speichern", von da aus zur Detailseite. 

"Diesen Straßenabschnitt löschen", sollte auf die Detailseite und sollte nur der User können, der den Straßenabschnitt auch angelegt hat. Welche Angaben ein anderer User zu einem Straßenabschnitt ändern können darf, muss ich noch überlegen.

**Comment by tabacha** [comment]
Das ist von der Benutzerführung total "Kraut und Rüben" wass passiert wenn ich erst einen Straßenabschntt bearbeite, dann die Hausnummer des Kindergartens ändere, dann auf den Button: Tempo 30 fordern klicke? Soll dann die Hausnummer nicht gespeichert werden?

**Comment by JulianLindner** [comment]
Wir haben entschieden, dass der Speichern Button bleibt wo er ist.
Der "Straßenabschnitt löschen"-Button muss aber definitiv wo anders hin, da man als Nutzer fast automatisch auf ihn klicken möchte um zu speichern. Idee: Oben rechts, neben die Hausnummern.

**Comment by tabacha** [comment]
Wenn dann über den Hausnummern, weil die Hausnummern ja jeztzt auch Straßennamen beinhalten sollen.

**Comment by JulianLindner** [comment]
Dann, bitte da über. (vielleicht neben "Status")
Wiebke merkt jedoch an, dass dieser nicht auftauchen soll, wenn der Straßenabschnitt eingeklappt ist.
