### ISSUE TITLE
Bearbeiten Straßenabschnitt, Angabe zu Hausnr. ändern

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#175]
nachdem ich ein paar Straßenabschnitte angelegt habe, merke ich, dass die Straßenabschnitt oft an Kreuzungen beginnen/enden, wo manchmal keine Hausnummer ist, das sollten die User angeben können.

Bitte ändern: 
"von Hausnummer" in "von Hausnummer/Kreuzung"
"bis Hausnummer" in "bis Hausnummer/Kreuzung"

und die Anzahl der erlaubten Zeichen im TextFreifeld entsprechend verlängern, sodass 
"Kreuzung und 2 Straßennamen" reinpassen

**Comment by tabacha** [comment]
@WiebkeADFC Bin mir etwas unsicher mit diesem Request. 

Erstmal muss ja in die von Hausnummer und bis Hausnummer jeweils nur eine Straße eingetragen werden, die zweite ergibt sich ja aus der Straße für die T30 beantragt werden soll selbst.

Dann kann es sein, dass die Kreuzung nicht eindeutig ist. z.B Hausbrucher Bahnhofstr. Ecke Wiedenthalter Bogen gibt es zweimal.

Außerdem macht es ja auch nichts den Abschnitt ein klein wenig größer zu wählen und die nächste Hausnummer hinter der Kreuzung zu wählen.

Was bedeutet das für den E-Mail-Text?

Im Moment erzeugen wir folgenden Text:

```
      `Ich ersuche Sie hiermit, an diesem an ${this.ANGR_ART[einr.type]} angrenzenden Straßenabschnitt ` +
      `${streetSection.street} von Hausnummer ${streetSection.house_no_from} bis Hausnummer ` +
      `${streetSection.house_no_to} Tempo 30 einzuführen.\n\n` +
```
Man könnte daraus z.B.
```
      `${streetSection.street} von Kreuzung/Hausnummer ${streetSection.house_no_from} bis Kreuzung/Hausnummer ` +
```
machen.

**Comment by WiebkeADFC** [comment]
"Außerdem macht es ja auch nichts den Abschnitt ein klein wenig größer zu wählen und die nächste Hausnummer hinter der Kreuzung zu wählen."
Ich habe bei ein paar Einrichtungen gesehen, dass in der Nähe der Kreuzung keine Hausnr. ist oder auf der anderen Seite der Kreuzung eine andere Straße oder keine STraße (T-Kreuzung) Es scheint mir, dass dies häufiger ist als zweimal dieselbe Kreuzungskombi

**Comment by WiebkeADFC** [comment]
E-Mailtext Vorschlag von dir finde ich gut. Kann ich aber leider erst richtig sehen, wenn ich das im Zusammenhang der E-Mail sehe.

**Comment by tabacha** [comment]
Wartet auf https://github.com/ADFC-Hamburg/adfc-t30-api/pull/82
