### ISSUE TITLE
Folge der Angabe "Alle Straßenabschnitte aufgeführt"

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#176]
Die Info, dass alle STraßenabschnitte aufgeführt sind, ist am wichtigsten für uns, damit wir aus den aktuellen Angaben zu STraßenabschnitten eine Kategorie für die Einrichtung ableiten können. Solange der Haken bei "Alle Straßenabschnitte aufgeführt" fehlt, muss der Stern blau sein, als Aufforderung die Einrichtung zu überprüfen. 

Bei Details
der Satz "Weitere angrenzenden Straßenabschnitte für die Tempo 30 gilt oder gelten sollte sind uns nicht bekannt."
hilft dem User allerdings nicht viel weiter, der kann ersatzlos gestrichen werden, wenn ein User angibt, dass alle Straßenabschnitte aufgeführt sind. 

Solange das Häkchen bei "Alle Straßenabschnitte aufgeführt" fehlt, soll der aktuelle Satz, der bei Details aufgeführt ist, erscheinen, aber bitte ohne das Warnzeichen. Das verwirrte die Testuser.

**Comment by JulianLindner** [comment]
Zurzeit wird der Stern orange (Handlungsbedarf), wenn bei einer Einrichtung bei mindestens einem Straßenabschnitt Tempo 30 fehlt.
Laut diesem Issue soll dass ja aber nicht passieren, so lange der Haken "alle Straßenabschnitte sind aufgeführt" nicht ausgewählt ist. Stattdessen soll der Stern bis dahin blau bleiben

**Comment by WiebkeADFC** [comment]
Nee @Julian, das ist schon richtig so, sobald für ein Straßenabschnitt "Hier fehlt Tempo 30" angegeben ist, soll der Stern der Einrichtung rot, sobald die Mail verschickt orange.

**Comment by Julian** [comment]
@WiebkeADFC please be a bit more careful with pings if possible :), you've pinged me a few times.

**Comment by WiebkeADFC** [comment]
@Julian Oh sorry, I´m not very familiar with github. I´ll take more care. Thank you for the kind hint.

**Comment by tabacha** [comment]
Ich schließe diesen Issue, und ihr macht bitte einen neuen auf, wenn nötig. Das mit den Sternen war hier nicht beschrieben.
