### ISSUE TITLE
Erfolgsmeldung nach E-Mail speichern oder absenden hinzufügen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#177]
Dein E-Mailentwurf wurde gespeichert. Du findest ihn unter "Meine Forderungsmails" wieder. Bitte lass uns am Fortgang deiner Forderung teilhaben, indem du bei "Einrichtung bearbeiten" den Tempo 30 Status und die Geschichte zum Straßenabschnitt änderst, wenn sich etwas tut.

oder 

Die E-Mail wurde versandt. Du findest sie unter "Meine Forderungsmails" wieder.

**Comment by tabacha** [comment]
Noch zu entscheiden: Als eigene Seite (wie die Logout: Willst du dich wirklich abmelden? Seite) oder als Nachricht die nach einiger Zeit verschwindet (vgl. https://material.angular.io/components/snack-bar/examples )

**Comment by WiebkeADFC** [comment]
Entscheide du bitte, je nach Aufwand, beides gut.
