### ISSUE TITLE
Meldeadresse -> Adresse umbenennen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#18]
Wenn die Nebenstelle, z. B. Sporthalle, eine andere Adresse als die Meldeadresse hat, wo soll die eingegeben werden?

**Comment by WiebkeADFC** [comment]
Könntest du zum Test eine neue Einrichtung mit einer Nebenstelle an Nicht-Meldeadresse einrichten, dass ich das mal sehen kann, bitte?

**Comment by tabacha** [comment]
Telefonisch besprochen, wir ändern den Text "Meldeadresse" in "Adresse"

**Comment by WiebkeADFC** [comment]
OK!
