### ISSUE TITLE
Sind Straße, PLZ und/oder Stadt nicht gepflegt in der E-Mail platzhalter einfügen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#182]
Idee: Wenn der User keine Straße, PLZ und/oder Stadt angibt, sollte in der E-Mail (an der Stelle wo die Addresse steht) ein Platzhalter für Kontaktdaten hinterlegt werden

**Comment by tabacha** [comment]
@WiebkeADFC ist das Sinnvoll?

**Comment by WiebkeADFC** [comment]
Ja, das ist sinnvoll, auch datenschutzmäßig sehr zu begrü´ßen.
