### ISSUE TITLE
Historie des Datensatzes anzeigen.

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#189]
Wir haben in der Datenbank eine Historie des Datensatzes unter by_the_record abgelegt, dieser ist z.B.  KiTa Aktive Erdmännchen              
```
kein Tempo 30 am 30.11.16
Buslininen: 20, 25, 600
Bustaktung mindestens 6 Fahrten/Std. in wenigstens einer Fahrtrichtung zur Hauptverkehrszeit
Mehrspurig 
```
Diese Infos könnten wir dem User irgendwo anzeigen.
Gewünscht?

**Comment by WiebkeADFC** [comment]
Ja, sehr gewünscht, z. B. als Kasten bei Details, Einrichtung

"Diese Angaben macht der Senat zu Tempo 30 an der Meldeadresse dieser Einrichtung"

**Comment by WiebkeADFC** [comment]
Ich habe gesehen, dass da auch Angaben, die von der LEA stammen, drin sind, deshalb hat Julian den Titel des Abschnitts geändert.
