### ISSUE TITLE
Tempo 30 fordern, keine Übernahme der Daten des Straßenabschnitts, vermutlich von jemand anderem angelegt

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#195]
Beispiel Schule Kielortallee (von Julian angelgt) und Kita Kratzbürste 
Bei Details auf Tempo 30 fordern geklickt, bei Überprüfungseite keinerlei Daten der Einrichtung/STraßenanschnitt
DAnn auch kein E-Mailentwurf

Bei Julian, der parallel in Kielerortallee arbeitet, geht alles. 

Version 40

**Comment by tabacha** [comment]
![Screenshot_20191021_154322](https://user-images.githubusercontent.com/1101544/67210573-9d2f6700-f419-11e9-81ed-a75093e2d67f.png)
@WiebkeADFC  Sieht bei mir gut aus. Oder ich habe das Problem nicht verstanden.

**Comment by tabacha** [comment]
@WiebkeADFC  Bitte mal F12 drücken (Developer Tools) und in die Console und/oder Network nachsehen  ob da Fehlermeldungen (rot) auftauchen, ggf. mit @JulianLindner  zusammen machen.

**Comment by tabacha** [comment]
@WiebkeADFC  habt ihr das noch auf dem Zettel? Mich wurmt es nicht weiter zu kommen, wenn ein Bug High-Priority ist, dann muss auch das nachstellen schnell gehen.

**Comment by JulianLindner** [comment]
Wir haben das ganze heute mit der Version 44 noch mal durchgeführt und der Fehler tritt nicht mehr auf.
Wir können beide die Seite gleichzeitig offen haben.
