### ISSUE TITLE
Karte und Liste: Button "Legende" über Karte und Liste

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#197]
die Legende und den Button dafür bitte über Karte und Liste anzeigen.

Karte/ Liste müssen dann jeweils nach unten verschoben werden wenn Legende geöffnet wird.

**Comment by tabacha** [comment]
@JulianLindner  hatte ich ausprobiert und hat mir nicht so gefallen, weil wir dann doppelten Platz wegnehmen. Der "Fehlender Einrichtung hinzufügen" Button sollte ja nach unten.

Das ist Usability halt IMHO auch immer ein Balance zwischen: 
- User die die Anwendung kennen und keine Legende brauchen (für die wäre es gut den Button unten zu haben)
- User die mehr Hilfe brauchen (für die wäre es gut, die Legende im zweifel sogar zu öffnen).

Bitte nochmal überdenken und Rückmeldung geben.

**Comment by JulianLindner** [comment]
Ja, bitte oben
