### ISSUE TITLE
Hinzufügen: Angabe "Träger" bei Daten zur Einrichtung

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#198]
Neue Spalte in der Datenbank bei Angaben zur Einrichtung, optional. 

Hat Testuserin angelegt und ist megapraktisch für die Kampagne, weil wir dann effizient mit Trägern zusammenarbeiten können.

**Comment by tabacha** [comment]
Wenn das ein Textfeld wird, muss man die Schreibweise beachten, sonst steht da bei 
- Kita1: Elbkinder 
- Kita2: Elbkinder eG
- Kita3: Elbkinder Vereinigung Hamburger Kitas gGmbH

**Comment by WiebkeADFC** [comment]
Wir haben keine Liste der relevanten Träger, könnte Julian bitten, diese zu recherchieren. 
Meinst du, dass die User die Liste der Träger pflegen? 
Kann zu low priority, wäre aber schade, wenn diese Angabe bei vielen nicht gemacht werden kann.

**Comment by tabacha** [comment]
Ich würde sage, wir pflegen die Liste im GIT und speichern an der Einrichtung nur eine Zahl. 

Vielleicht kann man die Liste ja auch bei LEA erfragen?

Ich würde dann folgenden Reihenfolge vorschlagen:

- Unbekannt
- <Hier kommen die uns bekannten Träger hin>
- Kein Träger, bzw. Träger bertreibt nur einen Kindergarten in Hamburg
- Täger ist nicht in der Liste aufgeführt

**Comment by tabacha** [comment]
Sobald ich eine Liste habe, würde ich das Umsetzen.

**Comment by WiebkeADFC** [comment]
@Julian, bitte Liste der Träger erstellen.

**Comment by WiebkeADFC** [comment]
@tabacha, es wäre ja megapraktisch, wenn die User die Liste der Träger selber erweitern könnten, wenn der Träger noch nicht drin ist?

**Comment by tabacha** [comment]
> 
> 
> @tabacha, es wäre ja megapraktisch, wenn die User die Liste der Träger selber erweitern könnten, wenn der Träger noch nicht drin ist?

Weiß nicht, birgt auch wieder die Gefahr von Doppeleintagungen, Tippfehlern etc. Ist halt ein Riesenaufwand für diese Information ein eigenes Modul zu machen.

**Comment by WiebkeADFC** [comment]
OK, dann lassen wir das. Ist wohl einfacher, ab und zu mal die Tabelle der Träger im Backend zu erweitern. DAnke.

**Comment by tabacha** [comment]
Hier sind auch die Träger aufgeführt
http://suche.transparenz.hamburg.de/dataset/kita-einrichtungen-hamburg10?forceWeb=true

**Comment by tabacha** [comment]
Folgende Träger sind in Hamburg mehr als 2 mal vertreten:
```
3 Akademie für Kinder AfK GmbH
3 Anneke Vogel
3 b kids kindergarten gGmbH
3 Die halben Meter gGmbH
3 Evangelische Kindertagesstätten Alten Eichen gGmbH
3 Evangelische Stiftung Alsterdorf
3 Ev.-Luth. Gemeinde der Hauptkirche St. Nikolai
3 Ev.-Luth. Kirchengemeinde Hamburg-Poppenbüttel
3 Frau Justyna Milewska
3 Frau Petra Use
3 Frau Svetlana Kabanova
3 Freie Christliche Bildungseinrichtungen gGmbH
3 Hamburger Kinderhafen GbR
3 Hamburger Kindertagesheime e.V.
3 Hort Altonaer Straße e.V./ G. Schmidt
3 Integrativo gGmbH
3 JUL gemeinnützige GmbH
3 Käptn Kaninchen GmbH
3 Kinderland Hamburg gemeinnützige Unternehmergesellschaft (haftungsbeschränkt)
3 Kinderstadt Kitas GmbH
3 Kindertagesstätte Pusteblume GmbH
3 Kita LSK Betriebsgesellschaft UG mbH & Co.KG
3 Little Ivy GmbH
3 Pedia gGmbH International
3 PMP Projekt Management Partner GmbH
3 SVE Hamburg Bildungspartner gGmbH
3 Villa Vivendi GbR
4 Akademikerbund Hamburg e.V
4 Erzbistum Hamburg
4 Ev.-Luth. Kirchengemeinde Eimsbüttel
4 Hamburger Institut für Berufliche Bildung
4 Kinderland Hamburg e.V.
4 Schmusebacke GmbH
4 Studierendenwerk Hamburg (AÖR)
4 Waldameisen gGmbH
4 Weltwissen-Kitas gGmbH
5 Apoidea reggio-orientierte Erziehung, Bildung und ganzheitliche Persönlichkeitsentfaltung e.V.
5 Deutsches Rotes Kreuz Hamburg Altona und MItte gemeinnützige Gesellschaft für Kinder, Soziales und Jugend KISO mbH
5 Katholische Pfarrei Seliger Johannes Prassek
5 Paula & Max Kindertagesstätten GmbH
5 Pedia gemeinnützige Bildungs-GmbH
6 FRÖBEL Bildung und Erziehung gGmbH
7 Asklepios Kliniken Hamburg GmbH Kindertagesstätten AKHH
8 Pestalozzi-Stiftung Hamburg
15 ASB Sozialeinrichtungen (Hamburg) GmbH
15 Hamburger Schulverein von 1875 e.V.
17 Deutsches Rotes Kreuz Kreisverband Hamburg-Harburg e.V.
17 WABE e.V.
18 Kinderwelt Hamburg e.V.
19 Deutsches Rotes Kreuz Kinder- und Jugendhilfe gGmbH
19 Rudolf-Ballin-Stiftung e.V.
19 SterniPark GmbH
24 Arbeiterwohlfahrt Landesverband Hamburg e.V.
26 Stiftung Kindergärten Finkenau
31 Ev. Luth. Kita-Werk Hamburg-West/Südholstein
58 Kirchengemeindeverband der Kindertageseinrichtungen im Ev.-Luth. Kirchenkreis Hamburg-Ost
177 Elbkinder Vereinigung Hamburger Kitas gGmbH

```
