### ISSUE TITLE
Abmelde Button auf Formularseite

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#22]
Einfach zu finden, wenn man schnell raus will aus der Anwendung. Die meisten werden das Tool ja nur sehr wenige Male nutzen, sodass sie die Wege nicht durch Gewöhnung kennenlernen werden.

**Comment by tabacha** [comment]
Wir müssen dann prüfen, ob eingaben geändert wurden. Wenn ja: Frage ob gespeichert werden soll. Ist recht Aufwendig

**Comment by tabacha** [comment]
Es gibt jetzt einen Abmelde Button
