### ISSUE TITLE
"Speichern" Abfrage vor Verlassen des Formulars? Testen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#23]
Geht sehr weit bei Nutzerfreundlichkeit und Frust vermeiden. Zur Verhinderung von Datenverlust/ Doppeltarbeit. Abfrage, ob Daten gespeichert werden sollen, wenn User auf Back-Pfeil klickt oder anderweitig das Eingabeformular verlässt, falls bis dahin ungespeicherte Daten eingegeben wurden.

**Comment by tabacha** [comment]
Hier wird das technisch beschrieben:
https://medium.com/front-end-weekly/angular-how-keep-user-from-lost-his-data-by-accidentally-leaving-the-page-before-submit-4eeb74420f0d

**Comment by tabacha** [comment]
TODO: Prüfen ob das überall greift.

**Comment by WiebkeADFC** [comment]
Soll das schon im Frontend geprüft werden? dann bitte Julian assignen

**Comment by tabacha** [comment]
Wenn jemand Zeit hat, wäre es toll, wenn es jemand ausprobiert, ich habe es selbst *nicht* getestet und rechne mit Fehlen, aber eine Übersicht: Hier fehlt es, da geht es, wäre prima. Bitte nach Möglichkeit die Seiten jeweils mit der Url benennen.

christopher hatte sich auch angeboten, tests zu machen. Aber ich packe Juilan mit drauf.

**Comment by WiebkeADFC** [comment]
Julian ist jetzt 2 Wochen im Urlaub.

**Comment by tabacha** [comment]
Test nacht auch erst Sinn, wenn ich das Backend eingebaut habe
