### ISSUE TITLE
Wiebke zu Admin Mailingliste

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#231]
https://ml-cgn06.ispgateway.de/mailman/listinfo/soziale-t30_lists.hamburg.adfc.de/

mit der Mailadresse: 
tempo30sozial@hamburg.adfc.de

damit ich die Mailingliste verwalten kann. Habe ich auch schon mal gemacht. 
Danke

**Comment by tabacha** [comment]
Hast du das Passwort für die Mailingliste? Oder hat das Jens? Oder sollen wir es zurücksetzen

Verwalten kannst du die Liste unter:
https://ml-cgn06.ispgateway.de/mailman/admin/soziale-t30_lists.hamburg.adfc.de

Wenn du das Passwort nicht mehr weisst und nicht in Erfahrung brignen kannst, dann schreib bitte an it-support@ham...

**Comment by WiebkeADFC** [comment]
ach jetzt verstehe ich, du hast hier die Mailingliste für die Projektgruppe Tempo 30 verlinkt. Ich erbitte bei der IT eine neue, nicht interaktive Mailingliste für die Infomails an die Nutzer des Tools. Die soll mit dem Tool verlinkt werden.
