### ISSUE TITLE
Förderung von "Bingo" Umweltlotterie

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#233]
Wir sollten die Förderung in unserem Tool anmerken. Die Idee war, das Logo rechts oben in der Ecke neben das T30 Herz.

**Comment by JulianLindner** [comment]
Wiebke bitte das Logo raussuchen und an Sven übermitteln oder hat er das schon?

**Comment by WiebkeADFC** [comment]
Bitte den Text: 
Die Kampagne wird gefördert von (Dann das Logo von Bingo.)
![BINGO-Logo](https://user-images.githubusercontent.com/46481622/67469740-e9162200-f64c-11e9-9c7e-dbcdb47d4ff7.jpg)
Danke.

**Comment by JulianLindner** [comment]
@WiebkeADFC ist die Formulierung "Die Kampagne wird gefördert von" nötig oder geht das ohne?

**Comment by JulianLindner** [comment]
Bitte den Hinweis "Die Kampagne wird gefördert von" vor dem Logo ergänzen

**Comment by WiebkeADFC** [comment]
Ja, der Hinweis ist nötig. Sonst sieht es aus, als wäre Bingo gleichberechtiger Anbieter des Tools.
