### ISSUE TITLE
Bug: "Meine Tempo 30 Eingaben" als Startseite, aber nicht im Menü

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#242]
Die Startseite meines Profils wiebke.hansen... ist "Meine Tempo 30 Eingaben" mit 4 Zeilen. 
Im Menü ist dieser Punkt allerdings nicht aufgeführt. Eine Default-Einstellung oder von einer älteren Registrierung gespeichert? 
Der Punkt fehlt auch dann noch im Menü, wenn ich in derselben Sitzung neue Straßenabschnitte angelegt habe oder eine Mail versandt habe. 
Er taucht auf, wenn ich eine E-Mail gespeichert habe. 

Soll: 
Der Menüpunkt soll für den User permanent erscheinen, sobald er einen E-Mailentwurf gespeichert hat oder eine E-Mail versand hat.

**Comment by tabacha** [comment]
Ich kann das im Moment nicht nachstellen.

**Comment by tabacha** [comment]
Vorschlag: Menüpunkt immer anzeigen und wenn der User darauf Klickt und keine Eingaben gefunden werden wird stattdessen eine Anleitung angezeigt

**Comment by tabacha** [comment]
Doch noch was gefunden. Hoffe der Bug ist weg. Bitte gründlich testen.

**Comment by WiebkeADFC** [comment]
Einverstanden mit dem Vorschlag. Wenn noch keine Forderungsmails, dann bitte TExt: 

Hier findest du deine Forderungsmails an die zuständigen Polizeikommissariate, sobald du eine E-Mail abgeschickt oder einen E-Mailentwurf gespeichert hast. Um eine Forderungsmail zu verfassen, gib zunächst die Informationen zu den Straßenabschnitten im Umfeld der Einrichtung ein (Klick auf Button "Bearbeiten" bei der jeweiligen Einrichtung). Dann kannst du auf der Seite "Details" der jeweiligen Einrichtung für jeden Straßenabschnitt, an dem Tempo 30 fehlt, auf den Button "Tempo 30 fordern" klicken.
