### ISSUE TITLE
Bug: Fehlermeldung bei E-Mail generieren

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#243]
Folgende Fehlermeldung erscheint, sobald man auf Tempo 30 fordern klickt. Man kann die E-Mail aber trotzdem verfassen oder die Einrichtung bearbeiten. Den Inhalt der Fehlermeldung verstehe ich sowieso nicht.
![grafik](https://user-images.githubusercontent.com/46481622/67467956-f7167380-f649-11e9-837a-64c207bc450e.png)

**Comment by tabacha** [comment]
Duplikat: #239

**Comment by tabacha** [comment]
Duplikat: #239
