### ISSUE TITLE
identische Einrichtunge können mehrfach hinzugefügt werden

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#246]
Einrichtung hinzufügen. Ich habe 2 Mal dieselbe Einrichtung mit demselben Name und Adresse hinzugefügt. Sie ist jetzt 2 mal in der Liste. 
Beispiel das fiktive Altenheim AABB am Alten Wall 10.
Wenn Name, ggf. Nebenstellte; Art der Einrichtung und Adresse identisch sind, sollte es nicht möglich sein, die Einrichtung nochmal anzulegen. 
Wir könnten die Funktion "Einrichtung hinzufügen" erst mal von der SEite nehmen und nach dem Fixen wieder anbieten.

**Comment by tabacha** [comment]
Ganz verhindern können wir es eh nicht. Da schreibt einer den Namen etwas anders und dann weißt du nicht ob es der gleiche oder ein anderer Kindergarten ist.

Ich würde den Button auf jeden Fall drinn lassen.

**Comment by WiebkeADFC** [comment]
Wir hatten am Anfang mal die automatische Anzeige von Einrichtungsnamen, das würde doch helfen, dass der Mensch erkennt, dass es die einrichtung schon gibt.
