### ISSUE TITLE
Bug: nach Klick "keine Dialogfenster mehr anzeigen" viele Buttons nicht anklickbar

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#248]
1. Bearbeiten, diesen Straßenabschnitt löschen. Danach in Dialogfenster "keine Dialogfenster mehr anzeigen" ausgewählt. 

Danach konnte ich nur noch auf "Neuen Straßenabschnitt hinzufügen" und "Alle Abschnitte aufgeführt" klicken, auf keinen anderen Button: nicht speichern, nicht Straßenabschnitt löschen, nicht im Menü.

Ich konnte erst wieder speichern als ich bei den mittlerweile drei geöffneten Masken für Straßenabschnitt anlegen die Pflichtdaten eingetragen hatte. 

Wenn ich dann wieder in bearbeiten gehe, kann ich die STraßenabschnitte immer noch nicht löschen. 

Auch nach erneutem Einloggen kann ich keine Straßenabschnitte löschen, aber ich kann scheinbar sonst alles machen. 

Ich meine, die Auswahl "Keine Dialogfenster" anzeigen" könnte abgeschaltet werden, bis der Bug behoben ist.

**Comment by tabacha** [comment]
Der Punkt: "Keine Dialogfenster mehr bearbeiten" wird vom Broser eingefügt, wir könnnen Ihn technisch nur dadruch entfernen, dass wir einen anderen Dialog nutzen. Ich habe das Gefühl, dass sind eigentlich hier 2-3 Bugs. Magst du das ausfplitten. 

Bei weilchem Eintrag war das? Wurde für den Abschnitt ggf. schon eine E-Mail verschickt? (dann ist das löschen nicht mehr möglich, der Bug ist das der Button noch da ist)

**Comment by WiebkeADFC** [comment]
Das war bei der Einrichtung AABB. Es kann sein, dass für einen der Abschnitte schon eine Mail versand wurde, aber sicher nicht für alle, die ich nicht löschen konnte. 
Jetzt geht das übrigens alles wieder, daher wären einzelne Issues auch nicht passend, oder? 

Ich habe auch gerade bemerkt, dass der Browser manchmal die Auswahl "Keine Dialogfenster mehr anzeigen" anzeigt und manchmal nicht. 
Der Satz heißt ja genau : Diese Seite daran hindern, weitere Dialoge zu öffnen. Vielleicht verhindert die Seite dann gleich ganz, auf Buttons zu klicken, die ein Dialogfenster zur Folge haben? 

Wir könnten auf die Seiten, wo man was speichern kann, einen Warnhinweis machen: "Manche Browser bieten in Dialogfenstern automatisch folgende Auswahl an: "Diese Seite daran hindern, weitere Dialoge zu öffnen". Bitte NICHT auswählen, da sonst einige Buttons nicht mehr geklickt werden können."

**Comment by tabacha** [comment]
Die Meldung wird vom Browser eingefügt, wenn mehrmals schnell hintereinander gleiche Dialoge geöffnnet werden. Das wird beim User eher nicht vorkommen.

**Comment by WiebkeADFC** [comment]
OK, dann würde ich das hier jetzt schließen und neue Issue öffnen, wenn einer der fehler noch mal vorkommen.
