### ISSUE TITLE
Daten große Anfragen aufbereiten und an PG schicken

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#25]
Verabredung: Wiebke bereitet die Daten auf und Sven schaut dass er das einpflegt.

**Comment by WiebkeADFC** [comment]
Hi Sven, 

ich habe die Daten von der Großen Anfrage in eine Tabelle kopiert, auf drei Tabellenblättern (neu Tempo 30 an sozialen Einrichtungen, weitere Tempo 30 Einrichtungen, Hinweise aus Bevölkerung). 
Die Verwertbarkeit ist nicht ganz so präzise wie bei der ersten Großen Anfrage, da die Daten gröber angegeben sind, z. B. keine Einrichtungsnamen. In der großen Anfrage sind die Einrichtungen einer Straße in einer Zeile zusammengefasst, das habe ich in mehrere Zeilen aufgedröselt. Aber dort sind die Streckenlängen von mehreren Einrichtungen in einer Straße als eine kumulierte Länge zusammengefasst.
 
Du wirst es sehen, vielleicht müssen wir noch beraten, wie wir mit einzelnen Daten umgehen. 
VG, Wiebke 
[Daten Große Anfrage T30sE Mrz 2019.xlsx](https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/files/3089562/Daten.Grosse.Anfrage.T30sE.Mrz.2019.xlsx)

**Comment by WiebkeADFC** [comment]
Hi Sven, 

ich habe die Daten von der Großen Anfrage in eine Tabelle kopiert, auf drei Tabellenblättern (neu Tempo 30 an sozialen Einrichtungen, weitere Tempo 30 Einrichtungen, Hinweise aus Bevölkerung). 
Die Verwertbarkeit ist nicht ganz so präzise wie bei der ersten Großen Anfrage, da die Daten gröber angegeben sind, z. B. keine Einrichtungsnamen. In der großen Anfrage sind die Einrichtungen einer Straße in einer Zeile zusammengefasst, das habe ich in mehrere Zeilen aufgedröselt. Aber dort sind die Streckenlängen von mehreren Einrichtungen in einer Straße als eine kumulierte Länge zusammengefasst.
 
Du wirst es sehen, vielleicht müssen wir noch beraten, wie wir mit einzelnen Daten umgehen. 
VG, Wiebke

**Comment by WiebkeADFC** [comment]
hier sind die Daten Tempo 30 an sozialen Einrichtungen vom Mai 2018:

csv, nur die Daten im 1. Tabellenblatt:

https://hh.adfc-clouds.de/index.php/s/XM5zbiC2pW625cR

Zeichensatz Unicode 8

Feldtrenner ;

Texttrenner "


Excel inkl. Legende im 2. Tabellenblatt:

https://hh.adfc-clouds.de/index.php/s/JFqtgT6f24FeAfe


Hier die neueren Daten Aktualisierung Tempo 30 an sozialen Einrichtungen vom Mrz 2019:

Excel:

https://hh.adfc-clouds.de/index.php/s/mwMCkyR4jccGAco

**Comment by WiebkeADFC** [comment]
Hallo @tabacha und @christopherost 
ich habe jetzt die Datentabelle soweit aufgearbeitet, wie ich es in diesem Stadium kann.
In der Tabelle sind enthalten: 

- die Daten, die wir im Mai 2018 von der Behörde erhalten haben. Bei diesen Datensätzen gibt es diverse Informationen, ob Tempo 30 an der Meldeadresse vorliegt, zeitl. Beschränkung dort, Busfrequenz und Linien, Mehrspurigkeit, gab es Anträge aus der Bevölkerung etc. 
- Weiterhin habe ich die Daten aus der Anfrage vom Mrz 19 integriert, im Wesentlichen wann Tempo 30 angeordnet und/oder eingeführt wurde. Die meisten Daten davon habe ich in bereits bestehende Datensätze vom Mai 2018 eingefügt. Einige wenige Einrichtungen habe ich auch neu angelegt. Dann fehlen die ganzen Extras aus der Anfrage vom Mai 2018.
- Weiterhin hat unsere Ansprechpartnerin beim Landeselternausschuss, Kita-Eltern, unsere Liste mit ihrer Kita-Liste verglichen, und uns 88 zusätzliche Kita-Adressen geschickt. Die sind enthalten, aber nur Einrichtungsart, Name, Adresse, Bezirk. 

In den Original Datensätzen vom Mrz 19 sind Angaben und Datensätze, die ich nicht übertragen konnte. Das muss ich mir auch noch mal mit jemandem angucken, aber da frage ich mal Jens, wie relevant die sind. 

Es gibt Spalten, aus denen die Herkunft der Information erkennbar ist. 

Aus den Angaben in den verschiedenen Spalten herzuleiten, welche Kategorie unsere Einrichtung bekommt, bzw. der Straßenabschnitt der Meldeadresse, ist nicht trivial und würde ich gerne besprechen, mit @christopherost oder mit euch beiden?

[Daten T30 alle soz Einr Mai 2018 2019-08-20.xlsx](https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/files/3520913/Daten.T30.alle.soz.Einr.Mai.2018.2019-08-20.xlsx)

**Comment by tabacha** [comment]
Daten sind jetzt aufbereitet. Werden nach dem Pull-Rquest eingespielt. Ich würde die by_the_record Daten gerne anzeigen. Da sollte ich (@tabacha) noch mit @WiebkeADFC  spechen.
