### ISSUE TITLE
Aussage zu Tempo 30

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#26]
Hallo Wiebke,
was hälst du davon, dass wir das Forumlar "Einrichtung" oder "Stand der Dinge (?)" 
um ein Klappfeld analog zu den Farben in #4 ergänzen?

Label des Klappfeldes: Stand der Verkehrsberühigung
Werte des Klappfeldes:

- Hier ist alles in Ordnung (nur Straßen mit Tempo 30 oder weniger im Umfeld)
- Hier besteht Handlungsbedarf (Straßen mit Tempo 40 oder mehr Umfeld)
- Es wurde Tempo 30 angeordnet aber noch nicht eingeführt
- Forderungen nach Tempo 30 wurden abgelehnt 

Wenn man "Hier ist alles in Ordnung" angibt, kann man keine E-Mail verschicken und bestimmte Felder die keinen Sinn machen mehr ausfüllen.

Ich bin mir noch nicht ganz im klaren, wie das bei abgelehnt ist: 
- Von wem Abgelehnt wurde das Abgelehnt (der CDU Abgeordnete im Bezirk vs. Europäsicher Gerichtshof mit was geben wir uns zufrieden?)
- Wann wurde das Abgelehnt? Wurde inzwischen neu Gewählt? Kann man es neu probieren?

**Comment by WiebkeADFC** [comment]
Ja, das finde ich sehr gut. 
Label Klappfeld gerne: Handlungsbedarf

Ablehnung durch die Behörde würde ich sagen. Wir oder die Paten müssen dann erst mal gucken, was wir daraus machen.

**Comment by WiebkeADFC** [comment]
OK, oder?
