### ISSUE TITLE
Zeitplanung

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#27]
Hi @tabacha , 
könnt ihr nach dem Programmierertreffen gestern schon etwas zur Zeitplanung sagen? Habt ihr ein Vorgehen dazu verabredet? 
VG, Wiebke

**Comment by tabacha** [comment]
Leider noch nicht wirklich. Wir wurden durch die Batchlor-Arbeit unterbrochen, da der andere Raum nicht frei war, konnten wir nicht umziehen. Aber wir wollen das per E-Mail weiter diskutieren
