### ISSUE TITLE
Version 50: "Fehler im Backend" Einrichtungen nicht angezeigt

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#274]
In der Version 50 meldet sich die Fehlermeldung "Fehler im Backend" und es werden weder Einrichtungen geladen, noch ist eine Anmeldung/ Registrierung möglich.

In Version 49 geht alles

**Comment by tabacha** [comment]
Bei mir geht alles ;-)



Entschuldigung: War ein Deployment Problem. Die Backend-Version 0.1.32 war nicht auf dem Server installiert

**Comment by JulianLindner** [comment]
Jo! geht wieder
