### ISSUE TITLE
Neue Einrichtung hinzugefügt: Position auf Karte falsch.

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#279]
Ich habe eine neue Einrichtung hinzugefügt "Kita Ausgedacht" in der Bogenstraße 20.
Sie wird allerdings auf der Karte auf dem Rathausmarkt angezeigt.

Nochmaliges eingeben der Adresse und speichern ändern daran nichts.

Der Bezirk ist dadurch auch falsch

**Comment by JulianLindner** [comment]
Ein manuelles Verschieben der Position ist möglich und wird wohl auch gespeichert!

**Comment by tabacha** [comment]
Seltsam. Bei mir geht es.

**Comment by tabacha** [comment]
Wenn das das nächste mal Aufritt bitte in den Developer-Tools (Taste F12) mal die Konsole ansehen, ob es da eine Fehlermeldung mit nominatim gibt. Diese bitte aufklappen und Screenshot.

**Comment by JulianLindner** [comment]
Edit: Beim Erstellen der Einrichtung wird die Position richtig angezeigt. 
Speichert man allerdings, wird die Einrichtung auf der Übersichtskarte am Rathausmarkt plaziert. Auch wenn man wieder in die Ansicht der Einrichtung selbst geht.
![grafik](https://user-images.githubusercontent.com/19272727/67686231-adee5880-f996-11e9-8d41-2f9df1b5345f.png)
