### ISSUE TITLE
Zwei Einrichtungen an selber Adresse: Auswahl über Karte nicht möglich

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#282]
Befinden sich im selben Haus mehrere Einrichtungen, kann man nur eine von beiden über die Karte anwählen, da die Sterne ja wahrscheinlich übereinander dargestellt werden.

Gibt es eine Möglichkeit das kurzfristig zu lösen? Ansonsten bräuchte man irgendwie ein kombinierten Kasten für beide Einrichtungen oder muss diese irgendwie leicht versetzt platzieren

**Comment by tabacha** [comment]
Man kann ja immer noch über die Liste die Einrichtung bearbeiten. 

Das Betrifft ca. 160 Einrichtungen.

**Comment by tabacha** [comment]
![Screenshot_20191028_162259](https://user-images.githubusercontent.com/1101544/67691693-4c7eb780-f99f-11e9-87a6-79ddef93022a.png)

Hab mal was "gebastelt" was die Positionen der Einrichtungen um 0.00015 Grad verschiebt, wenn die Position gleich ist. Hier ein Screenshot von der Brecht Schule

**Comment by JulianLindner** [comment]
mega gut, Danke!

**Comment by JulianLindner** [comment]
kann geschlossen werden?

**Comment by tabacha** [comment]
Nein! Ich spiele das in eine Backend Version ein und dann könnt ihr das bitte noch mal testen.

**Comment by tabacha** [comment]
Bitte in 
https://tools.adfc-hamburg.de/t30-paten/version0.0.51/#/sozEinrKarte
testen.

Wenn es so gut ist, spiele ich das in das Live-System ein, dafür bitte das Ticket wieder auf mich stellen. Das können wir dann aber nicht mehr rückgängig machen.

**Comment by JulianLindner** [comment]
Ich finds super so!
