### ISSUE TITLE
Detailseite: Leerzeichen fehlt zwischen einrichtung.status und t30StatusLongText

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#287]
In der Tabelle.
Kriege das gerade selber irgendwie nicht hin

**Comment by tabacha** [comment]
Das sieht bei mir aber okay aus. Mach bitte mal nen Screenshot

**Comment by JulianLindner** [comment]
![grafik](https://user-images.githubusercontent.com/19272727/67752228-ef344600-fa32-11e9-8ecb-885f060f803d.png)

**Comment by tabacha** [comment]
Ah, okay hinter dem Status Text, ich hatte zwischen Icon und Status Text gesucht.
