### ISSUE TITLE
Erklärtext von Register bitte an die selbe Stelle im Profil

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#289]

**Comment by JulianLindner** [comment]
Meinst du den? @WiebkeADFC 

"Name, E-Mail und Passwort werden für die Registrierung benötigt. Die weiteren Felder enthalten keine Pflichtangaben. Name, Email, Straße, Hausnummer und PLZ werden ggf. in die Forderungsmail an das zuständige Polizeikommissariat übernommen. Die Telefonnummer hilft dem Kampagnenteam, ggf. schnell Kontakt mit dir aufzunehmen."
