### ISSUE TITLE
Detailseite: "T30 fordern"-Button mehr hervorheben

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#301]
Tester Georg hatte den Button "T30 fordern" nicht auf Anhieb gefunden. Gut wäre wenn wir ihn besser hervorheben würden.

Z.B. in Blau

**Comment by tabacha** [comment]
Blau ist eigentlich die "Primary Farbe" die soll in einem Dialog nur einmal vorkommen und da soll es dann weiter gehen. Bei uns können aber z.B. zwei Straßenabschnitte zu Fordern sein. Wir könnten den Button accent  einfärben, also so  wie bei E-Mail versenden. Sonst gerne auch mal hier schauen: https://material.angular.io/components/button/examples

**Comment by JulianLindner** [comment]
"accent" sieht gut aus. 
Die weissen Buttons sind eben deutlich weniger sichtbar, als die irgendeiner Farbe
