### ISSUE TITLE
Email-Erstellung: Stichwort merken

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#302]
Es wäre gut wenn das Stichwort wieder eingefügt würde, wenn man die Email erst speichert und dann später absenden will.
Wenn das technisch möglich ist

**Comment by tabacha** [comment]
Bedeutet halt, dass wir das Backend ändern müssen, oder wir speichern es im Browser. Dann ist es aber nicht da wenn der User es bei der Arbeit anfängt und zu Hause zu Ende bringt.

**Comment by JulianLindner** [comment]
Ich würde sagen, dass ein Speichern im Browser dafür völlig ausreichend ist.
