### ISSUE TITLE
Email-Erstellung: Bei Klick auf Button "korrigieren" Warnung weg

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#303]
Möchte man von der Email-Erstellungsseite zurück zur Einrichtung bearbeiten Seite kommt ein Warn-Pop-Up, dass nicht gespeicherte Änderungen nicht gespeichert werden.

An dieser Stelle kann man ausser dem Stichwort allerdings ja eh nichts bearbeiten.
Diese Warnung hat Tester Georg irritiert

**Comment by tabacha** [comment]
Die Warnung kommt "nur" wenn man das Stichwort bereits eingegben hat.
