### ISSUE TITLE
Satz zu Daten (war Kommunikation nach Klick auf Button in Karte oder Liste, wenn noch nicht eingeloggt)

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#31]
Wenn User nicht eingeloggt ist und etwas an den Daten zu einer Einrichtung ändern möchte oder Tempo 30 beantragen, dann ein Kommunikationsfeld, das auf Einloggen vorbereitet.
Text: Danke, dass du dich an unserer Kamapagne "Tempo 30 an sozialen Einrichtungen" beteiligen möchtest. Damit wir sicher gehen können, dass die Tempo-30-Forderungen oder die Änderungen zu einer Einrichtung ernsthaft sind, bitten wir dich, dich einzuloggen bzw. dich erst zu registrieren. Wir .... "Satz zu Daten".
Button "Weiter"

**Comment by tabacha** [comment]
Was bedeutet: "Satz zu Daten"

**Comment by WiebkeADFC** [comment]
Damit meinte ich wohl den Satz zum Datenschutz, den wir noch nicht haben.

**Comment by tabacha** [comment]
@JulianLindner @WiebkeADFC  Bitte Satz zu Daten ergänzen
