### ISSUE TITLE
TestErgebnis Realversand E-Mail: Absenderin erhält Mail delivery Failure Mail für eigene E-Mail adresse

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#314]
und hat die Mail an sich selbst in CC auch nicht bekommen. 
Hier die Fehlermeldungsmail: 

> von: Mail Delivery System <Mailer-Daemon@tools.adfc-hamburg.de>
> Datum: 1. November 2019 um 14:40:27 MEZ
> An:ERSETTZT@yahoo.de
> Betreff: Mail delivery failed: returning message to sender
>
> This message was created automatically by mail delivery software.
>
> A message that you sent could not be delivered to one or more of its
> recipients. This is a permanent error. The following address(es) failed:
>
> ERSETZT@yahoo.de
>    host mx-eu.mail.am0.yahoodns.net [188.125.72.73]
>    SMTP error from remote mail server after end of data:
>    554 5.7.9 Message not accepted for policy reasons.  See https://help.yahoo.com/kb/postmaster/SLN7253.html

mime-attachment

Reporting-MTA: dns; tools.adfc-hamburg.de

Action: failed
Final-Recipient: rfc82;ERSETZT@yahoo.de
Status: 5.0.0
Remote-MTA: dns; mx-eu.mail.am0.yahoodns.net
Diagnostic-Code: smtp; 554 5.7.9 Message not accepted for policy reasons.  See https://help.yahoo.com/kb/postmaster/SLN7253.html

mime-attachment
Betreff: 
Tempo 30 für Friedrichsberger Straße 18 bis 18 an KiTa Frieberg
Von: 
ERSETZT@yahoo.de>
Datum: 
01.11.2019, 14:40
An: 
pk31@polizei.hamburg.de
Kopie (CC): 
ERSETZT@yahoo.de, tempo30sozial@hamburg.adfc.de

Sehr geehrte Damen und Herren,
mein Name ist ... Kindergartens "KiTa Frieberg", Friedrichsberger Straße 18, 22081 Hamburg.

Im Umfeld dieser Einrichtung fehlt leider noch Tempo 30.

Ich ersuche Sie hiermit, an diesem an den Kindergarten angrenzenden Straßenabschnitt Friedrichsberger Straße  von Kreuzung Eilbektal bis Kreuzung Dehnhaide Tempo 30 einzuführen.

Begründung:
Haupteingang und An- und Abreiseverkehr

Sicherheit der Kitakinder auf dem Weg zur und von der Kita, besonders beim Verlassen der Kita durch das Tor, das direkt zur Straße liegt. Viele Kinder kommen mit dem Laufrad oder Fahrrad, schnell rollt mal ein Ball auf die Straße oder ein kleines Kind läuft versehentlich mit hinaus, wenn eine andere Familie das Gelände verlässt.

Aus meiner Sicht sind die Kinder, die im Umfeld des Kindergartens am Verkehr teilnehmen, nicht ausreichend vor dem schnellen KFZ-Verkehr geschützt.
Die KFZ-Fahrer*innen müssen durch ein geringeres Tempo in die Lage versetzt werden, besondere Aufmerksamkeit walten zu lassen.
Die Änderung für den KFZ- und Busverkehr halte ich angesichts des Sicherheitsgewinns für angemessen. Der Sicherheit muss Vorrang vor Geschwindigkeit gewährt werden.

In der Hauptverkehrszeit ist die Friedrichsberger Straße so voll Verkehr, dass selbst Tempo 30 oft nicht möglich ist. Außerdem befinden sich sowohl die Bushaltestelle als auch eine Ampel in unmittelbarer Nähe des Eingangs zur Kita. Somit kann der Bus seinen Fahrplan zur Hauptverkehrszeit sowieso nicht einhalten und fährt mit Verspätung.

Laut §45 Absatz 9 Satz 4 Ziffer 6 der StVO in Verbindung mit der Verwaltungsvorschrift zu §45 StVO soll zum Schutz besonders schützenswerter Personen im Umfeld sozialer Einrichtungen,
also dort wo Haupteingänge sind oder Quell- und Zielverkehr zur Einrichtung herrscht, regulär Tempo 30 gelten, ohne dass eine besondere Gefahrenlage erwiesen ist.

Vielen Dank und mit freundlichen Grüßen

ERSETZT
--
Diese E-Mail wurde durch das Tempo 30-Tool des ADFC-Hamburg verschickt, mehr Infos dazu unter:
https://hamburg.adfc.de/tempo30sozial

**Comment by tabacha** [comment]
@WiebkeADFC  bitte keine Persönlichen Daten in den Issue-Tracker von Github

**Comment by tabacha** [comment]
Ich schreibe gleich mal was dazu an Euch per E-Mail. 

Grund dafür ist, dass ihr ausgerechnet einen yahoo User genommen habt und diese eine besonderen Spam Check nutzt, der gegen Internet-Richtlinien verstößt.

**Comment by tabacha** [comment]
>wäre eine Weiterleitung der Antwort über unsere Server nicht
> wirklich datenschutzrechtlich schön, insbes. weil wir dann im Sinn
> des
> TKG als Dienstleister/Provider verstanden werden könnten, was einige
> Rechtsfolgen mit sich bringen könnte.
> Daher wäre ich für die sauberste Alternative, die Sven benannt hat:
>
> > Eine Alternative wäre, die E-Mail mit einem festen Absender, z.B. 
> > tempo30sozial@... zu verschicken, den Reply-To Header auf den
> > eigentlichen 
> > Absender zu setzen und ggf. eine Textblock an den Anfang zu
> > stellen,
> > in der 
> > wir die Polizei bitten an den Antragssteller zu antworten.

**Comment by tabacha** [comment]
Lasst und die Lösung mit dem Textblock und  den Reply-To Header umsetzen.

@WiebkeADFC  @JulianLindner Ich brauche den Text für den Textblock und die Entscheidung ob wir diesen Textblock in der GUI Anzeigen wollen oder nicht und ob er vom User editierbar sein soll oder nicht. 

Editierbar und Anzeigen wäre technisch am einfachsten.

Ich wäre dafür das Ticket auf "normal-prio" herunterzustufen. Da es nur wenige User (yahoo Domain und noch ein paar wenige andere) betrifft und weil es prinzipiell funktioniert (es wird eine E-mail an die Polizei geschickt und auch richtig in der DB verzeichnet.

**Comment by tabacha** [comment]
Besprochen mit @WiebkeADFC : Text am Anfang soll nicht editierbar sein.

Wenn ihr wollt, können wir auch den Footer ggf. mit einem anderen Text versehene und  nicht editierbar machen. Dieser ist  im Moment:
> --
>Diese E-Mail wurde durch das Tempo 30-Tool des ADFC-Hamburg verschickt, mehr Infos dazu >unter: https://hamburg.adfc.de/tempo30sozial

**Comment by WiebkeADFC** [comment]
CC: nicht nur tempo30sozial@---, sondern zusätzlich "E-Mail Absender des Gesuchs"

Introtext direkt nach der Anrede in der E-Mail an die Polizei: 
diese E-Mail wurde mit Hilfe des Online-Tools "Tempo 30 an sozialen Einrichtungen" des ADFC Hamburg verschickt. Bitte senden Sie Ihre Antwort auf das Gesuch an "E-Mail Absender des Gesuchs" und tempo30sozial@hamburg.adfc.de.

weiter geht es mit "Mein Name ist..." Anfangsbuchstaben des Satzes auf Großschreibung ändern. 

Text im Footer der E-Mail "Diese E-Mail wurde durch das Tempo 30-Tool des ADFC-Hamburg verschickt, mehr Infos dazu unter:
https://hamburg.adfc.de/tempo30sozial" ändern in: 
"Mehr Informationen zur Kampagne "Tempo 30 an sozialen Einrichtungen" des ADFC Hamburg: 
https://hamburg.adfc.de/tempo30sozial"

Erklärtext über E-Mail anpassen: 
Den Satz" Wir setzen deine bei der Registrierung angegebene E-Mailadresse als Absender ein."
ändern in 
"Wir setzen deine bei der Registrierung angegebene E-Mailadresse in CC und bitten im E-Mailtext die Polizei, an deine E-Mailadresse zu antworten."

Bitte bei Absender unter die Adresse eine Zeile mit der Absender-E-Mailadresse hinzufügen. 

Erklärtext vor "E-Mail absenden" 
"Diese E-Mail wird unter Angabe Deiner E-Mailadresse als Absender an das für die Einrichtung zuständige Polizeikommissariat übermittelt. Dein Name und deine Adresse werden ebenfalls als Absenderinformation in die E-Mail übernommen, sofern du sie im Profil angegeben hast und nicht aus der E-Mail gelöscht hast. Durch Klick auf "Speichern und E-Mail absenden" stimmst Du diesem Vorgang zu."
ändern in: 
Diese E-Mail wird unter Angabe Deiner E-Mailadresse als Antwort-E-Mailadresse an das für die Einrichtung zuständige Polizeikommissariat übermittelt. Dein Name und deine Adresse werden ebenfalls als Absenderinformation in die E-Mail übernommen, sofern du sie im Profil angegeben hast und nicht aus der E-Mail gelöscht hast. Durch Klick auf "Speichern und E-Mail absenden" stimmst Du diesem Vorgang zu.

**Comment by tabacha** [comment]
Mit Wiebke besprochen:

Zuerst Block

Diese E-Mail wurde mit Hilfe des Online-Tools "Tempo 30 an sozialen Einrichtungen" des ADFC Hamburg verschickt. Bitte senden Sie Ihre Antwort auf das Gesuch an "E-Mail Absender des Gesuchs" und tempo30sozial@hamburg.adfc.de.

Dann die normale Anrede usw.

**Comment by tabacha** [comment]
Wartet auf: 
https://github.com/ADFC-Hamburg/adfc-t30-api/pull/89
https://github.com/ADFC-Hamburg/flexapi/pull/46
