### ISSUE TITLE
Testuserin hat Stichworteingabe übersehen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#315]
kann das noch etwas hervorgehoben werden? DAnke

**Comment by tabacha** [comment]
In der Version 1.0 ist beim Button ein Hinweis, was falsch ist. 

Es ist ein wenig Kontraprodukiv alle Felder die ein User übersieht hervorzuheben. Denn dann sehen alle wieder gleich aus. Ich hatte damals das Stichwort ganz nach unten angesiedelt, das wurde von Julian nach oben verschoben.

**Comment by JulianLindner** [comment]
Wiebkes Idee dabei, dass nach oben zu schieben war, zu verhindern, dass Leute mit viel Mühe die ganze Seite durch arbeiten und dann erst feststellen, dass sie die Email nicht absenden können, da sie das Stichwort nicht haben

**Comment by tabacha** [comment]
@WiebkeADFC  Was machen wir jetzt hiermit?

**Comment by WiebkeADFC** [comment]
Du hast mir ja vorhin am Telefon erklärt, dass du noch Änderungen an dem Vorgang vorgenommen hast. Damit ist das OK und können wir schließen
