### ISSUE TITLE
Verlauf nach Klick auf Buttons

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#32]
Gilt für Buttons, die Änderungen an den Daten verursachen oder zu Tempo 30 fordern führen.

Wenn noch nicht eingeloggt, dann vorerst siehe hier: 
 https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/issues/31

        Button: Hier ist schon ausreichend Tempo 30 (Farbe wechselt von blau auf grün)
und
        Button "Die Tempo 30 Schilder sind aufgestellt" (Farbe wechselt von gelb auf grün)
"Bist du sicher, dass an allen angrenzenden Straßenabschnitten mit Haupteingängen und/oder An- und Abreiseverkehr zur Einrichtung Tempo 30 gilt?"
nach Auswahl Ja:
"Danke! Wir ändern die Informationen und die Farbe zur Einrichtung entsprechend." 
nach Auswahl Nein: 
"Danke für deine Beteiligung! Dann belassen wir die Informationen und die Farbe zur Einrichtung vorerst." 

        Button: Ich möchte hier Tempo 30 fordern (Klick auf Button führt zum Formular, schon vorausgefüllt mit der Einrichtung?)
- Hier nicht "Bist du sicher,.."  sondern einfach die Formularseite. Da wird ja oben auch irgendein hilfreicher Text stehen. 

        Button: Hier ist nicht ausreichend Tempo 30 (Farbe wechselt von blau auf rot)
"Bist du sicher, dass an einem der angrenzenden Straßenabschnitten mit Haupteingängen und/oder An- und Abreiseverkehr Tempo 30 fehlt?"
nach Auswahl Nein: 
"Danke für deine Beteiligung! Dann belassen wir die Informationen und die Farbe zur Einrichtung vorerst."
nach Auswahl Ja: 
"Danke! Wir ändern die Informationen und die Farbe zur Einrichtung entsprechend.
Kannst du angeben, an welchen Straßenabschnitten Tempo 30 fehlt? Dann leiten wir dich zum Formular der Einrichtung."
Nach Auswahl Nein: 
"Danke für deine Beteiligung und bis bald" (oder irgendwohin zurück gehen lassen, z. B. auf die Website der Kampagne?)
Nach Auswahl Ja:
Wechsel zum Formular, wo die Straßenabschnitte, für die Tempo 30 gefordert wird, eingegeben werden können. 
"An welchen Straßenabschnitten fehlt Tempo 30? gibt es dort einen Haupteingang und/oder An- und Abreiseverkehr?"
Freifeld mit Bezeichnung: "Straße", daneben Freifeld mit Bezeichnung "ggf. mit Hausnummern von bis", daneben Abfrage mit Checkbox "Haupteingang" "An- und Abreiseverkehr" (Mehrfachantwort erlauben) 
Button "weiterer Straßenabschnitt" (dann wird weitere Zeile für STraße, Hausnr. und Checkboxen aufgemacht.)
Ich hab jetzt noch keine Vorstellung davon, wie es danach mit Danke und möchtest du gleich die Forderungsmail abschicken usw. abläuft. Das müsste ja irgendwie im Formularablauf geschehen.

**Comment by tabacha** [comment]
anderer Ablauf jetzt
