### ISSUE TITLE
Email: "Anmerkungen zum Busverkehr" wenn kein busverkehr

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#320]
Wenn an einer Straße kein Busverkehr ist, kommt in der Email trotzdem 

"Anmerkungen zum Busverkehr:
null"

Wäre gut wenn das dann komplett rausgenommen würde, oder etwas steht wie: "An dieser Stelle kein Busverkehr"

**Comment by tabacha** [comment]
Für mich nicht nachstellbar.
Wenn ich bei:

https://tools.adfc-hamburg.de/t30-paten/version1.0.1/#/einrichtung/view/2

eine Forderung mache, erscheint werder der Text "Anmerkung zum Busverkehr" noch ein null.

**Comment by JulianLindner** [comment]
für mich im Moment auch nicht nachstellbar.
