### ISSUE TITLE
Liveversion auf aktuellste Version

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#321]
Bitte die aktuelle Version, (am besten) nach Änderung des Datums zum Stichwort, in die Liveversion einspielen, damit die Kampagne los gehen kann.

**Comment by tabacha** [comment]
Bin ich gearade bei.

**Comment by tabacha** [comment]
So, sollte erledigt sein. Mir wäre es lieb, wenn ich sowas in Zukunft eher am abend machen kann. 

Änderungen die nicht im Testsystem getetet wurden, spiele ich grundsätzlich NICHT ein.
