### ISSUE TITLE
Straßenabschnitt: Bei "Kreuzung" keine Sonderzeichen möglcih

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#322]
Möchte man einen Straßenabschnitt anlegen der an einer Kreuzung beginnt, kann man in dem Feld keine Sonderzeichen angeben. In vielen Straßennamen kommen ja aber Bindestriche vor.

**Comment by tabacha** [comment]
Verstehe ich nicht. Ich habe hier Sonderzeichen eingegen:

https://tools.adfc-hamburg.de/t30-paten/version1.0.1/#/einrichtung/view/2

**Comment by JulianLindner** [comment]
Kann ich jetzt auch. Weiß nicht warum das da nicht ging
