### ISSUE TITLE
Mailerstellung: Mouseover Texte über Mail-Adressen falsch

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#323]
Durch die Umstellung auf das neue Mailkonzept stimmen die Mouseovertexte über den Adressen nicht mehr und müssen ans neue Konzept angepasst werden.

zB:
Absender: "Von dieser Adresse wird die Mail versandt. Die Antwort geht an deine bei der Registrierung eingegeben Mailadresse und das Kampagnenteam"

CC: "Du und das Kampagnenteam erhalten eine Kopie der Email. An diese soll auch die Antwort der Polizei geschickt werden."

**Comment by tabacha** [comment]
@JulianLindner  mach mit gerne einen Pull-Request dazu. Die Mouse Over Texte solltest du in der  html Datei finden.
