### ISSUE TITLE
Liveversion 1.0.1: Kein Ansehen fremder abgeschickter Mails möglich

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#329]
Es ist zurzeit nicht möglich eine, von einem anderen User abgesendete, Mail anzugucken. Es erscheint eine Fehlermeldung ohne Text.

![grafik](https://user-images.githubusercontent.com/19272727/68753565-8e496800-0605-11ea-845b-55d043fe0fa3.png)

**Comment by tabacha** [comment]
Bitte immer bei sowas meldungen wie, welche E-Mail an welcher Stelle, URL.

Gruß
Sven

**Comment by tabacha** [comment]
Scheint nur so zu sein, wenn man nicht angemeldet ist.

**Comment by JulianLindner** [comment]
https://t30forderung.hamburg.adfc.de/#/einrichtung/view/683
kommt tatsächlich nur vor, wenn man nicht angemeldet

**Comment by tabacha** [comment]
@JulianLindner  wenn du Zeit hast, wäre es super, wenn du versuchts das einmal in Testsystem nachzustellen. Wenn es dort auch so ist, ist es ein Backend-Problem. Ansonsten ein Config-Problem.

Gruß
Sven

**Comment by JulianLindner** [comment]
Tritt nur in der Liveversion, nicht in der Testversion auf!

**Comment by tabacha** [comment]
Ist hoffentlich behoben. Bitte testen.

**Comment by JulianLindner** [comment]
Jo! Geht danke!
