### ISSUE TITLE
Straßenabschnitte nicht löschbar

### ISSUE THREAD

**Issue by JulianLindner** [ADFC-Hamburg/adfc-t30-paten-frontend#330]
Löscht man einen Straßenabschnitt auf der Bearbeitenseite ist er zunächst weg.
Wenn man aber speichert, taucht der Abschnitt auf Detailseite und auch auf der Bearbeitungsseite wieder auf.

Version 1.0.1 und 1.0.2 getestet

**Comment by tabacha** [comment]
Am 2019-11-13 12:12, schrieb JulianLindner:
> Löscht man einen Straßenabschnitt auf der Bearbeitenseite ist er
> zunächst weg.
> Wenn man aber speichert, taucht der Abschnitt auf Detailseite und auch
> auf der Bearbeitungsseite wieder auf.
> 
> Version 1.0.1 und 1.0.2 getestet

Hallo Julian,
welchen Straßenabschnitt hast du gelöscht?



Gruß
Sven

**Comment by JulianLindner** [comment]
Liveversion: KiTa Billstedter Hauptstraße
beide Straßenabschnitte (insbesondere Straßenabschnitt Test)

**Comment by tabacha** [comment]
https://tools.adfc-hamburg.de/t30-paten/version1.0.2/#/einrichtung/view/502

Hat keine Straßenabschnitte.

**Comment by JulianLindner** [comment]
tut mir Leid, hatte das in der Liveversion getestet.
Tritt aber bei mir in der Testversion genau so auf!

https://tools.adfc-hamburg.de/t30-paten/version1.0.2/#/einrichtung/view/502
Straßenabschnitt "Test" hatte ich schon gelöscht
