### ISSUE TITLE
Anwendung nicht Nutzbar im Internet Explorer

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#333]

**Comment by tabacha** [comment]
https://blog.angularindepth.com/angular-and-internet-explorer-5e59bb6fb4e9

**Comment by tabacha** [comment]
Hallo @WiebkeADFC ,
wie gehen wir damit um? Wir könnten versuchen den IE zu unterstützen, aber wirklich  Sicher stellen dass es überall geht, kann ich nicht. Dafür müsstet ihr auch aufem IE testen (was schwierig wird, wenn wir die Gst auf Linux umgestellt haben).

Mein Vorschlag: Eine Klare Aussage, dass man bitte Chrome oder Firerfox nutzen soll.

**Comment by WiebkeADFC** [comment]
Hi @tabacha, ich kann da nur deiner Einschätzung folgen. also fügen den Hinweis ein.

**Comment by WiebkeADFC** [comment]
Ich habe den Hinweis bei Tipps zur Anwendung in der Code geschrieben, aber vergessen einen Pull request anzulegen, ist jetzt direkt im Master drin.
