### ISSUE TITLE
 zeitliche Beschränkung des Tempolimits

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#34]
**Kategorien, für die wir Rückmeldung von den Usern annehmen wollen:** 

- zusätzliche Einrichtung/Nebenstelle hinzfügen (Einrichtungsart, Name, ggf. Nebenstelle, Adresse, Bezirk, aktuelles Tempolimit (ggf. zeitliche Beschränkung), wie viel Bus/Stunde/Fahrtrichtung, Buslinien, Grund für Verlangsamung Bus?, wie viele Spuren/Fahrtrichtung)
- Korrektur bestehender Einrichtung (Geopunkt, Einrichtungsart, Name, ggf. Nebenstelle, Adresse, Bezirk, aktuelles Tempolimit (zeitliche Beschränkung), ab 6 Busse/Stunde/Fahrtrichtung, Buslinien, wie viele Spuren/Fahrtrichtung)
- Liegen an der Einrichtung Gründe für Sowieso-Verlangsamung der Busse vor?

**Comment by tabacha** [comment]
Können wir das Schließen?

**Comment by WiebkeADFC** [comment]
zusätzliche Einrichtung und Korrektur geht ja über "Bearbeiten" 
Dort fehlen noch folgende Angaben:

**Comment by tabacha** [comment]
Der Bezirk wird automatisch anhand der Posistion berechnet. Da muss niemand etwas eingeben.

Fehlt als: ggf. zeitliche Beschränkung des Tempolimits

**Comment by WiebkeADFC** [comment]
Der Bezirk wird automatisch anhand der Posistion berechnet. Da muss niemand etwas eingeben.: cool

**Comment by WiebkeADFC** [comment]
ToDo: 
"zeitliche Beschränkung des Tempolimits" hinzufügen bei "Bearbeiten" und "Details". 

Vorschlag: bei Bearbeiten ein neues freies Texteingabefeld hinzfügen, nicht noch einen zusätzliches Tempo-30-Status: 
Titel: ggf. zeitliche Beschränkung des Tempolimits (z. B. Mo-Fr, 6 - 22 Uhr)
