### ISSUE TITLE
Daten aus Webtool dem Kampagnenteam zur Verfügung stellen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#343]
Mit Sven besprochen:

Wiebke und Julian hilft es sehr bei der Kommunikation mit den Usern und dem Überblick über die Kampagne, wenn sie einige Daten gesammelt bekommen: 

1. Liste aller User mit Name, E-Mail, Telefon und Registrierungsdatum (falls es das gibt)

2. Liste der Straßenabschnitte mit allen zugehörigen Daten, welcher User (Name, E-Mail) ihn angelegt/bearbeitet hat, zu welcher Einrichtung er gehört

3. Liste aller E-Mails, Entwurf oder versandt, welcher User (Name, E-Mail) gespeichert oder versandt hat, zu welchem Straßenabschnitt und welcher Einrichtung

Sven schlug vor, jede Nacht so eine Abfrage zu machen und auf dem ADFC-Laufwerk zu speichern. Hier ist der Ordner: 

G:\Projekte\Einzelne Projekte\2017_Tempo30\T30_sozial\Tool Karte\Daten Webtool

Danke!

**Comment by tabacha** [comment]
@WiebkeADFC @JulianLindner Daten sollten da autoamtisch erscheien. Bitte Ticket schließen, wenn okay.

**Comment by WiebkeADFC** [comment]
finde ich gut und funktioniert! Danke!
