### ISSUE TITLE
Workflow nach den Buttons in den Klappfenstern, "Neue Einrichtung angeben", "Korrektur" und Änderung "Stand der Dinge" für eine Einrichtung

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#36]
Für diese drei Kategorien haben wir noch nicht beraten, wie es weitergeht. Soll es eine Moderation der Änderungen geben? 
Mein Vorschlag ist ohne Moderation, weil ich keinen Schimmer habe, wie wir das überhaupt überprüfen sollen: 
Mein Vorschlag ist, dass bei allen Eingabenarten die Änderungen direkt in DB und Karte übernommen werden und die Kampagne benachrichtigt wird, z. B. 2x/Tag (9 h und 14 h), welche Änderungen es gab. Die Benachrichtignug ist wichtig, damit wir die Kampagne gut controllen können (Wird sie angenommen und ist die Qualität wie gewünscht?)

Ist es möglich, die Eingaben auch jeweils wieder rückgängig zu machen, wenn sie sich als falsch herausstellen? Oder die Vorversion zu speichern, damit man in den alten Daten nachgucken kann?

**Comment by tabacha** [comment]
Besprochen: Bei Änderungen soll sofort eine E-Mail verschickt werden in der Möglichst auch gleich die Kontatkdaten des Users stehen.
