### ISSUE TITLE
Landkarte soziale Einrichtungen erstellen

### ISSUE THREAD

**Issue by tabacha** [ADFC-Hamburg/adfc-t30-paten-frontend#4]
https://tools.adfc-hamburg.de/rike/VersionWiebke/toggle_test.html
nur ohne den Tempo30 Buffer

**Comment by tabacha** [comment]
Lieber Sven,

ich habe mir folgendes für Karten überlegt. Mein wichtigstes Kriterium 
ist eine angenehme Ansicht und Führung für den unbedarften Nutzer.

Bei allen Karten die Auswahlfelder, welche Daten angezeigt werden 
können, bitte neben die Karte, inklusive jeweilige Legende (die fehlt im 
Moment und muss von PG T30 geliefert werden).

  * eine Karte, die nur die Umweltdaten enthält, ohne Anträge und
    Tempolimit. Die Daten für NO2 und Feinstaub werden jetzt in dem
    Maßstab, sodass man ganz Hamburg sieht, sehr dick dargestellt.
    Können Feinstaub PM 10 und PM 25 zusammengefasst werden? Die Linien
    sind identisch.

  * eine Karte mit einfacher Darstellung der Orte privater Anträge oder
    sozialer Einrichtungen T30 ja/nein

private Anträge, Symbol Punkt:

- solange nicht positiv beschieden alle in rot (egal,ob mit unserem Tool 
erstellt oder abgeschickt (die jetzige Aufteilung in rot und blau macht 
keinen Sinn, passt überhaupt nicht mit den Informationen zusammen, dass 
431 Anträge gestellt wurden))
- private Anträge positive Bescheide oder anderweitig T30 eingeführt: 
türkis (Hebt sich besser ab als blau)

Soziale Einrichtungen, Symbol Stern:
- ü30 in rot.
- bis T 30 in türkis.

Anpassung der Farben, wenn sich der Status des Antrags oder der 
Einrichtung ändert. Übernahme weiterer Anpassungen der Daten.

Daneben Box mit Auswahl, welche der vier Kategorien sichtbar sind.


  * eine Karte für die privaten Anträge Aktion

https://hamburg.adfc.de/verkehr/themen-a-z/tempo-30/laeuft/karte-antraege-und-belastungen/#12/53.5911/9.9903

so wie jetzt, aber entschlackt um Tempolimit, POI, und Feinstaub PM 10 
und 25 zusammengefasst.

Farben:

rot für gestellte Anträge, lila für erzeugte Anträge, türkis für positiv 
beschiedene Anträge

Daneben Box mit Auswahl:

Anträge, Lärm Tag, Lärm Nacht, NO2, Feinstaub mit jeweiligen 
Farbzuordnung, (von PG T30 zusammengestellt)


  * eine Karte für Aktion soziale Einrichtungen

ohne Umweltdaten. Unterscheidung in

- Art der Einrichtung über Symbol, wie Henrike vorbereitet hat, nur ein 
kompakteres Symbol für Kita. Ich such was raus.

- bis T30 türkis

- ü T30 rot

Informationen über wie viel Bus und Spuren könnten in den Aufklapptext 
pro Einrichtung. Das muss ich noch in der Gruppe klären.

Box mit Auswahlfeldern daneben, wie bei den anderen Karten auch .



  * eine Karte mit den Tempolimits

mit dem Hinweis, dass diese aufgrund fehlerhafter Datengrundlage/ 
Aktualisierungen an einigen Stellen falsch sein können. Angabe Daten 
wann von wem und Legende, was die Farben bedeuten.

Dieser Layer sieht nicht sehr ansprechend aus. Wenn man einen Maßstab 
einstellt, sodass Hamburg als Ganzes im Fenster zu sehen ist, sind die 
Linien zu dick. Kann das geändert werden?

letzte Priorität, ich würde mit der PG T30 gerne klären, ob wir die 
überhaupt brauchen.


Soweit erst mal

LG, Wiebke

**Comment by tabacha** [comment]
Reicht ein Layer Chooser wie hier?  https://leafletjs.com/examples/layers-control/

**Comment by WiebkeADFC** [comment]
Unterscheidung: Orte, von denen die Behörde sagt, alles gut, und Orte, von denen wir sagen, alles gut, etc. 

Unterscheidung durch Farbe und/oder Form

ADFC ausreichend max T30: türkis
Behörde ausreichend T30: andere Farbe (noch mal prüfen, ob OK)
kein Tempo 30

Rückmeldung für: hier fehlt noch T30 oder hier braucht keiner mehr T30 zu beantragen.

**Comment by WiebkeADFC** [comment]
guck mal in dieser Datei hier: 

[Symbole Karte T30sE.pdf](https://github.com/ADFC-Hamburg/adfc-t30-paten-frontend/files/3080269/Symbole.Karte.T30sE.pdf)

**Comment by tabacha** [comment]
Perfekt. Damit kann ich was Anfangen

**Comment by tabacha** [comment]
Folgende Farben:

-  T30 → (R 5, G 83, B 250) = bitte überprüfen Farbcode: 0553fa
-  nicht T30 → (R 239, G 20, B 13) = Handlungsbedarf, Forderung stellen Farbcode: ef140d
-  Meldung „nicht ausreichend T30“: Forderungsmail abgeschickt: (R 247, G 171, B 5) Farbcode f7ab05
-  Meldung „ausreichend T30“ oder T30 eingeführt (mit oder ohne Forderung): (R 68,
G 249, B 23) Farbcode 44f917
- T 30 angeordnet, aber noch nicht eingeführt: (R 231, G 255, B 8) = beobachten e7ff08
- Forderung abgelehnt: (RGB 000) Farbcode 000000

**Comment by WiebkeADFC** [comment]
Alle gecheckt, alle korrekt. Danke!

**Comment by tabacha** [comment]
Erste Version:

https://tools.adfc-hamburg.de/t30-paten/map/version0.3.1/

Fehler/Wünsche die eindeutig mit der Karte zu tun haben bitte dort aufmachen: 

https://github.com/ADFC-Hamburg/adfc-t30-paten-map/issues

**Comment by WiebkeADFC** [comment]
Das ist ja echt URALT : ) Close ich mit Dank an dich @tabacha
