### ISSUE TITLE
automatisches Logout

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#45]
wenn man lange untätig war.

**Comment by tabacha** [comment]
Ist zwar im Moment so, dass der Token nur 2h gültig ist, aber Ist das wirklich wünschenswert? Ich habe da wenig Angst. Die meisten werden das zu Hause machen und wenn sie aus welchen Gründen 10h das Browser-Fenster geöffnet haben, warum sollen sie dann sich neu anmelden müssen?

**Comment by tabacha** [comment]
siehe auch #90

**Comment by WiebkeADFC** [comment]
Ich habe da auch kein Problem mit.

**Comment by tabacha** [comment]
TODO: Tokengültigkeit mehr als 2h, Renewal von Token

**Comment by bensteffen** [comment]
Habe dazu hier einen längeren Kommentar hinterlassen:

https://github.com/ADFC-Hamburg/flexapi/pull/23
