### ISSUE TITLE
Einheitliche Schrifttype

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#46]
Bitte die gerade Schriftar wie zum Beispiel bei in den Buttons wählen

**Comment by JulianLindner** [comment]
@tabacha wo sind denn die Schriften definiert? Ich finde die CSS dafür nicht?

**Comment by tabacha** [comment]
Anschein muss man bei allen html tags die nicht Angular Material Design 
nutzen eine entsprechende Material Css Class hinzufügen

Also statt

<h1>xxxx</h1>

Nun

<h1 class="mat-h1" >xxxx</h1>

so verstehe ich auf die schnelle das was hier:


https://material.angular.io/guide/typography


steht.

Aber vielleicht gibt es auch noch einen anderen Weg.


Hast du das Frontend inzwischen mit

ng serve

am laufen?

Dann kannst du das mit den Browser Developer Tools untersuchen.

Gruß Sven

Am 12. August 2019 17:21:08 schrieb JulianLindner <notifications@github.com>:

**Comment by tabacha** [comment]
Telefonische Rückmeldung ist okay.

**Comment by WiebkeADFC** [comment]
Das sieht super aus!!!!
