### ISSUE TITLE
Token nach Registrierung veraltet

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#48]
nach dem Registrieren, kann man laut Text und Eingabebox auch einen Token eingeben, in der Mail, die übrigens sofort kam, ist aber nur ein Link zum draufklicken, kein Token (halte ich auch nicht für nötig). 
Seite nach dem Registrieren bitte entsprechend anpassen. 

Du erhälst in Kürze eine E-Mail mit einem Link, der deine Registrierung bestätigt. Bitte schaue ggf. auch in den Spam Ordner. Bitte klicke innerhalb von 12 Stunden auf den Link, da wir sonst die Daten wieder löschen.
Vielen Dank!

**Comment by tabacha** [comment]
Es gibt Benuter die aus Sicherheitsgründen kein HTML akzeptieren bei denen ist der Link dann zum Teil so lang, dass er umgebrochen wird. Deshalb habe ich das mit dem Token gemacht. 

Außerdem ist das aus Sicherheitsgründen *nie* eine gute Idee auf so einen Link zu klicken (auch wenn das viele Benutzer machen). Deshalb würde ich das eigentlich gerne weiter so anbieten. Aber das ist auch ein Backend-Ding.

**Comment by WiebkeADFC** [comment]
wie ihr meint, bin einverstanden, muss nur konsistent sein.
