### ISSUE TITLE
merkwürdige Seite nach Registrieren bestätigen 

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#49]
![grafik](https://user-images.githubusercontent.com/46481622/62716486-88d6f300-ba02-11e9-986e-32a8e1b38c04.png)

**Comment by WiebkeADFC** [comment]
Dialog weiterführen: 
Vielen Dank. Deine Registrierung ist bestätigt.
Mit Klick auf "Weiter" kommst du zum Tempo-30-Forderungs-Tool.

**Comment by tabacha** [comment]
https://github.com/ADFC-Hamburg/adfc-t30-api/issues/21
