### ISSUE TITLE
Button taub, wenn als wiebke.hansen eingeloggt

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#50]
Bei "Meine Tempo 30 Eingaben" passiert nichts, wenn ich als wiebke.hansen@ eingeloggt, die Stift-und E-Mail-Buttons klicke

**Comment by tabacha** [comment]
Seltsam. Ist das immer so? Oder hattest du vorher einen Fehler? Kannst du mal in der Browser-Entwickler- Javascript Konsole öffnen und nachschauen ob du da einen Fehler siehst?

https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers

**Comment by WiebkeADFC** [comment]
geht jetzt
