### ISSUE TITLE
Reihenfolge und Umbenennung des Menüs, Landingpage nach Login

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#51]
1. Karte der sozialen Einrichtungen
2. Liste der sozialen Einrichtungen
3. Meine Tempo-30-Forderungsmails (Umbennen bitte)
4. Mein Profil
5. Abmelden

Überlegen: Meine Tempo 30 Forderungen könnten auch mit ins Profil. 

(Für den Erstnutzer angenehmer, wenn er auf der Karte landet als auf ner leeren "Meine Tempo 30 Forderungen)

**Comment by WiebkeADFC** [comment]
Ändet die Umbenennung von einem Menüpunkt etwas in den Bezügen?

**Comment by tabacha** [comment]
> Ändet die Umbenennung von einem Menüpunkt etwas in den Bezügen?

Die Frage verstehe ich nicht.

**Comment by tabacha** [comment]
Der Fall, ich will eine Eingabe von mir wieder editieren, wird (hoffentlich) pro User häufiger vor kommen als der andere Fall.

Wir können nach dem Login auch sowas machen, wie: 

Wenn noch keine Forderung vorhanden -> Liste 
Wenn Forderungen -> Forderungsliste

Ich finde die Texte für die Tabs zu lang. Das ist jetzt schon ein Problem.

**Comment by WiebkeADFC** [comment]
Menüpunkte gekürzt:
  1. Karte soziale Einrichtungen
  2. Liste soziale Einrichtungen
  3. Meine Forderungsmails (Umbennen bitte)
  4. Mein Profil
  5. Abmelden

"Wenn noch keine Forderung vorhanden -> Liste
Wenn Forderungen -> Forderungsliste"
Gute Idee, warum auf Liste und nicht auf Karte?

Bezüge: wenn wir jetzt die Namen von Menüpunkten ändern, ob dann an anderer Stelle Probleme auftreten.
