### ISSUE TITLE
Detailseite: Grafik Infos zu einem Straßenabschnitt

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#57]
wenn es geht bitte die Blöcke zu je einem Straßenabschnitt deutlicher grafisch hervorheben, z. B. farbliche Unterlegung/ Kasten...

**Comment by JulianLindner** [comment]
In diesem Issue geht es um die Seite "Details" nicht um "Bearbeiten".

Bei "Bearbeiten" sieht das wirklich gut aus, bei "Details" fehlt sowas noch.

**Comment by WiebkeADFC** [comment]
doppelt mit neuem Issue
