### ISSUE TITLE
Einblenden / Ausblenden von Nutzerführung 

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#59]
Oben einen Erklärt-Text einfügen: 

Tipps zur Anwendung: 
1. Check der sozialen Einrichtung: Bitte wähle die Einrichtung über die Suchfunktion, die Liste oder die Karte aus und klicke "Bearbeiten". Gibt dort alle angrenzenden Straßen mit Haupteingang oder An- und Abreiseverkehr zur Einrichtung mit dem jeweiligen Tempo-30-Status ein. 
2. Tempo 30 für eine Einrichtung fordern bei Klick auf "Details".

**Comment by tabacha** [comment]
Ist mir irgendwie zu mächtig und nimmt auf kleinen Bildschirmen viel Platz ein, ggf. mit schließen/ausblenden Funktion?

**Comment by WiebkeADFC** [comment]
OK, Standardmäßig eingeblendet und dann "ausblenden"/"einblenden" Option. 

Tipps zur Anwendung ("einblenden"Button)
