### ISSUE TITLE
Tempo 30 fordern, Stand der Dinge umbenennen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#63]
in "Verlauf der Tempo-30-Forderung"

**Comment by WiebkeADFC** [comment]
Der Text unter dem Eingabefeld ist gut, abe zu weit unten, sieht man nicht. Direkt unter "VErlauf der Tempo-30-Forderung"?
Sind sie schon in Kontakt mit der Einrichtung, mit der Polizei, hat ein Politiker dafür/dagegen etwas gesagt?

**Comment by tabacha** [comment]
Ich hab dem mal weniger Platz gegeben.

**Comment by tabacha** [comment]
Wiebke schau dir da mal an. Wird in der Version 0.21 geändert sein.

**Comment by WiebkeADFC** [comment]
Hab ich mir angeguckt, der Abstand ist immer noch recht groß, aber durch die anderen Änderungen, einfügen einer Überschrift zur Foderungsmail, viel übersichtlicher. Also OK. Danke
