### ISSUE TITLE
Tempo 30 fordern: mehr Abstand vor der E-Mail

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#64]
Zur besseren Gliederung, das "Von" geht fast in das TExtfeld von Stand der Dinge über

**Comment by tabacha** [comment]
Ich habe in der Version 0.21 noch einen Linie eingefügt. Ist das so gut?

**Comment by WiebkeADFC** [comment]
Ja

**Comment by tabacha** [comment]
Dann darfst du das nächste mal auch das Ticket schließen ;-)
