### ISSUE TITLE
Klären! Bearbeiten: Nebenstelle ???

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#66]
Das verstehe ich schon gar nicht mehr, mit Datenmodell abgleichen? Ich weiß nicht mehr, wie die Abläufe für Nebenstelle mit anderer Adresse verabredet waren, sorry. Sollte für einen neuen Standort mit anderer Adresse eine neue Einrichtung angelegt werden?

das versteht man leider nicht: 
"ggf. anderer Standort/ Zweigstelle/ Nebengebäude (bei Namensgleicheit zu eine andreren Einrichtung/Standort ausfüllen)
z.B. wenn es drei Standorte gibt und bei zweien Tempo 30 Sinn macht, dann bitte für jeden von diesen einen eigenen Antrag ausfüllen und hier jeweils die Bezeichnung des Standortes angeben"

**Comment by tabacha** [comment]
Je Nebenstelle soll als eigne soziale Einrichtung aufgeführt werden. Wir haben für die Straßenabschnitte im Moment keine Geo-Koordinaten. Wenn jetzt eine Turnhalle von der Schule in einem anderen Polizei Gebiet liegt, dann gibt das Konfussion. Bitte schreibe, wie wir das den User klar machen wollen.

**Comment by WiebkeADFC** [comment]
Wenn eine Nebenstelle als eigene soziale Einrichtung aufgeführt werden soll, dann könnte man die Felder "Name der Einrichtung" und "Nebenstelle" auch zusammenführen. Dann unterscheiden sich die Namen auch eindeutig in unserer Datenbank, was ja mehrere Vorteil hat, meine ich. Titel des Eingabefeldes: 
"Name der Einrichtung, ggf. Bezeichnung der Nebenstelle (Turnhalle, Mensa, Zweigstelle...)"
Erklärtext und Eingabefeld: Jede Nebenstelle einer Einrichtung mit einer eigenen Adresse muss als eigene soziale Einrichtung angelegt werden. 

Userführung: Tipps zur Anwendung ergänzen um 
3. Soziale Einrichtungen, die hier noch nicht aufgeführt sind, können über den entsprechenden Button bei der Liste oder der Karte der sozialen Einrichtungen hinzugefügt werden. 
4. Jede Nebenstelle (z. B. Turnhalle, Mensa, Zweigstelle) einer Einrichtung mit einer eigenen Adresse muss als eigene soziale Einrichtung angelegt werden.

**Comment by tabacha** [comment]
Was versprichst du dir davon die Felder zusammenzulegen?

**Comment by WiebkeADFC** [comment]
Eine eindeutige Unterscheidbarkeit der Datensätze "Schule" und "Mensa der Schule an anderer Adresse" und leichtere Nutzerführung. Wenn der Name nur den Namen der Einrichtung enthält, zieht das Tool ja automatisch die Adresse davon, obwohl die Nebenstelle ja gerade dadurch definiert ist, dass sie an einer anderen Adresse ist. 
Vielleicht ergibt sich das auch alles, wenn die Erkärungen etwas eindeutiger werden.

**Comment by WiebkeADFC** [comment]
Ich habe das als Bug definiert, weil die Nutzerführung so unverständlich ist, dass es wie ein Fehler ist.
