### ISSUE TITLE
Text Registrierungs E-Mail

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#67]
Bitte ändern in: 

Hallo,

bitte klicke hier, um deinen Account bei der Kampagne des ADFC Hamburg "Tempo 30 an sozialen Einrichtungen" zu aktivieren.

Viel Spaß! 

(noch nen Hinweis auf Datenschutzregeln und ne Signatur?)

**Comment by WiebkeADFC** [comment]
Signatur: 

**Tempo 30 an sozialen Einrichtungen**
Eine Kampagne des ADFC Hamburg

www.hamburg.adfc.de/tempo30sozial
tempo30sozial@hamburg.adfc.de

Allgemeiner Deutscher Fahrrad-Club
Landesverband Hamburg e. V.
Koppel 34 - 36
20099 Hamburg

Ansprechpartnerin
Wiebke Hansen
Tel: (040) 32 90 41 15

**Comment by tabacha** [comment]
Als Backend-Ticket angelegt.
