### ISSUE TITLE
Kategorie "Kindergaten" umbenennen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#75]
in Kita

**Comment by tabacha** [comment]
Abkürzungen finde ich nicht gut. Und die frage ist auch, wo genau dir das aufgefallen ist und das geändert werden soll. Bei Kita denke ich immer an Kirchentag. Wenn dann Kindertagesstätte.

**Comment by WiebkeADFC** [comment]
OK, Kindertagesstätte
gefunden bei Bearbeiten, im Aufklappmenü bei Art der Einrichtung.

**Comment by tabacha** [comment]
@WiebkeADFC Was ist hier noch zu tun?

**Comment by WiebkeADFC** [comment]
Der Fehler besteht noch bei der Kategorie "Kindertagesstätte / Kindergarten" fehlt das zweite r bei Kindergarten. Ursprung wahrscheinlich das Dropdown bei Bearbeiten einer Einrichtung,
