### ISSUE TITLE
Tempo 30 Formular, klären "Mindestens ein Standort geht auf....

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#8]
Wiebke:  Abfrage "Mindestens ein Ausgang geht auf... " und den Ausrufe-Zeichen-Text dazu würde ich weglassen. Damit schränken wir ja selber die Forderungsmöglichkeiten ein. Das soll mal schön die Polizei begründen, warum sie kein Tempo 30 einführt.

Sven: Das sehe ich anders und sollten wir noch mal besprechen. Wenn wir das machen, 
kann die Polizei dem ADFC den Vorwurf machen, dass wir die Gesetzeslage nicht 
kennen und wild Anträge stellen.

**Comment by WiebkeADFC** [comment]
ich denke an Fälle, die wir im Einzelnen gar nicht so absehen können, z. B. das Schulgebäude hat eine lange Wand mit vielen Klassenräumen an einer Tempo 50 Straße, aber keinen Ausgang. Schüler erleiden trotzdem Lärm und schlechte Luft bei geöffneten Fenstern. Ich würde ungern die Praktikabilität für "unsere" User einschränken, um die Polizei vor ein bißchen mehr Arbeit zu schützen. Stattdessen die User über eine ordentliche Erläuterung der Bedingungen für Tempo 30 auf der Website lenken.

**Comment by tabacha** [comment]
Wiebke: Hatten wir da jetzt eine Klärung?

**Comment by WiebkeADFC** [comment]
Nein, noch nicht, gerne morgen beim Treffen der PG T30  mit Jens. 
Vorschlag: wir ändern diese Texte in die StVO-konforme Logik: Umfeld der Einrichtung und erläutern ung. so: Straßenabschnitte, an denen ein Haupteingang zur Einrichtung liegt oder in denen viel Ziel- und Quellverkehr zur Einrichtung ist. 
Außerdem gerne den Text, wenn das Häkchen nicht gesetzt ist, etwas entschärfen.
