### ISSUE TITLE
Bearbeiten, Button "Straßenabschnitt löschen" verschieben

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#84]
um aus Versehen Löschen vorzubeugen, weil die Leute denken, dass sie damit den Straßenabschnitt speicher. 
Z. B. in etwas kleiner rechts oben neben die Hausnummern des Straßenabschnitts.

**Comment by tabacha** [comment]
Es gibt noch ein Rückfrage ob man WIRKLICH den Straßenabschnitt löschen will. Ich halte das für ausreichend.

**Comment by WiebkeADFC** [comment]
Auch dann kann der Nutzer ja nur flüchtig lesen und meinen, es ginge im speichern. Ich finde es ungünstig einen Löschen Button dahin zu packen, wo man einen Speichern-Button gewöhnt ist. Aber die Priorität ist gering, da aufmerksame Nutzer den Fehler ja gar nicht machen.

**Comment by tabacha** [comment]
Hast du dir das in der aktuellsten Version daraufhin noch einmal angeschaut?

Wohn würdest du den Button schieben wollen?

Gruß Sven
Am 7. Oktober 2019 12:00:14 schrieb WiebkeADFC <notifications@github.com>:

**Comment by tabacha** [comment]
Duplicate #173
