### ISSUE TITLE
Details, Erklärtext zu Forderungsmail hinzufügen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#85]
Unter die Bereichsüberschrift "Angrenzende Straßenabschnitte..."
den Erklärtext: 
Hier kannst du für die einzelnen Straßenabschnitte jeweils eine Tempo-30-Forderungsmail an das zuständige Polizeikommissariat generieren, wenn diese im Bereich "Bearbeiten (Button)" mit dem Status "Hier fehlt Tempo 30" markiert wurden.

**Comment by tabacha** [comment]
Auf der Ansichtsseite oder auf der Bearbeiten Seite?

**Comment by tabacha** [comment]
Ah, ich sehe in der Überschrift steht "Details" ..
