### ISSUE TITLE
Menü, Link zur Kampagnenseite einfügen

### ISSUE THREAD

**Issue by WiebkeADFC** [ADFC-Hamburg/adfc-t30-paten-frontend#87]
hamburg.adfc.de/tempo30sozial

**Comment by WiebkeADFC** [comment]
öffnen in New tab

**Comment by tabacha** [comment]
Wie soll der Menüpunkt heißen? Wie wollen wir ihn dort einbinden? Die anderen Menüpunkte sind Tabs das ist ewas doof, weil sich da kein Tab öffnet

**Comment by WiebkeADFC** [comment]
dann ist ein Menüpunkt vielleicht nicht hilfreich. 
Bei weiterem Nachdenken meine ich, dass diese Funktion doch nicht so wichtig ist. Wenn jemand auf die Kampagnenseite will, findet er sie schon. Die meisten haben die Seite wahrscheinlich sowieso parallel geöffnet. 

Möglich wäre auch eine Art Signatur auf jeder Seite ganz unten: 
Dieses Webtool hilft dir, Forderungsmails für Tempo 30 an Straßenabschnitten, die an Hamburger sozialen Einrichtungen liegen, an das zuständige Polizeikommissariat zu verfassen. Das Webtool ist Teil der Kampagne des ADFC Hamburg "Tempo 30 an sozialen Einrichtungen". Und dann die Kampagnenseite verlinken.

**Comment by tabacha** [comment]
Da kommt ein 404 Page not found bei dem Link

**Comment by WiebkeADFC** [comment]
Das liegt daran, dass die Seite noch nicht freigeschaltet ist, die muss ich noch fertig machen. Ich schicke den Link dann noch mal.

**Comment by tabacha** [comment]
Brauchst du nicht, der Link ist drinn.

**Comment by WiebkeADFC** [comment]
ich halte dieses Issue jetzt für geklärt, schiebe es beim Project T30sozial in die Spalte "Beachten beim Test vor Kampagnenstart".

**Comment by tabacha** [comment]
Ich schließe es, es bleibt trotzdem auf dem Board
